<tr>
    <!--BREADCRUMB PATH-->
    <td class="" style="height: 136px; background: url(&quot;/images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;"><div id="bcPath"> <a href="/" class="l4 b">Home Page</a> &gt; <span class="l4on">Documentation</span> </div></td>
    <td><div class="bcPath3" title="" style="background: url(&quot;/images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">&nbsp;</div></td>
</tr>
<tr>
    <td class="" colspan="2" ><!--CATEGORY LIST-->
    <div  title="" style="background:url(&quot;/images/advanced_search/top_6b.jpg&quot;) left top no-repeat;">
    <div id="doc1">
    
      <ul class="dul1">
      	<li><a href="documentation/filter?type=text&key=txt&subtype=hw">Hundertwasser Texts and Manifestos</a></li>
      	<li><a href="documentation/show?type=biography&key=bio">Biography</a></li>
      	<li>Exhibitions
        	<ul class="dul2">
              <li> <a href="documentation/show?type=one_exhibition&key=one_ex&quest_filter=1">One-man exhibitions</a>
                <ul class="dul3">
                  <li><a href="documentation/show?type=one_exhibition&key=one_ex&quest_filter=2">Travelling exhibitions</a></li>
    
                  <li><a href="documentation/show?type=one_exhibition&key=one_ex&quest_filter=3">World Travelling Museum Exhibition</a></li>
                  <li><a href="documentation/show?type=one_exhibition&key=one_ex&quest_filter=4">Albertina Graphic Exhibition</a></li>
                </ul>
              </li>
	          <li> <a href="documentation/show?type=group_exhibition&key=group_ex">Group exhibitions</a> </li>
    	    </ul>
      	</li>
      	<li>Literature
      		<ul class="dul2">
           		<li>Hundertwasser Bibliography
                	<ul class="dul3">
                    	<li><a href="documentation/show?type=monograph&key=mono">Monographs</a></li>
                    	<li>Exhibition Catalogues
                      		<ul class="dul3">
                          		<li><a href="documentation/show?type=catalog_exhibition&key=cat_ex&quest_filter=1"><span>Catalogues</span> – One-man exhibitions</a></li>
                           		<li><a href="documentation/show?type=catalog_exhibition&key=cat_ex&quest_filter=2"><span>Catalogues</span> – Travelling exhibitions</a></li>
                            	<li><a href="documentation/show?type=catalog_exhibition&key=cat_ex&quest_filter=3"><span>Catalogues</span> – World Travelling Museum Exhibition</a></li>
                             	<li><a href="documentation/show?type=catalog_exhibition&key=cat_ex&quest_filter=4"><span>Catalogues</span> – Albertina Graphic Exhibition</a></li>
                        	</ul>
             		 	</li>
                	</ul>
            	</li>
            	<li><a href="documentation/filter?type=text&key=txt&subtype=nothw">Texts on Hundertwasser</a></li>
             	<li><a href="documentation/show?type=article&key=article_id">Press clippings</a></li>
        	</ul></li>
        <li><a href="documentation/filter?type=audio&key=audio">Audio</a></li>
        <li><a href="documentation/filter?type=video&key=video">Video</a></li>
        <li><a href="documentation/filter?type=gallery&key=gallery">Image Gallery</a></li>
        <li><a href="documentation/show?type=document&key=doc_id">Documents</a></li>
      </ul>
      </div>
      </div>

      </td>
</tr>