<tr>
    <!--BREADCRUMB PATH-->
    <td class="" style="height: 136px; background: url(&quot;/images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;">
      <div id="bcPath"> 
         <a href="/" class="l4 b">Home Page</a> &gt; 
         <a href="/documentation" class="l4 b">Documentation</a> &gt;
         <span class="l4on"><?php echo $this->title?></span>
      </div>
    </td>
    <td><div class="bcPath3" title="" style="background: url(&quot;/images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">&nbsp;</div></td>
</tr>
<tr>
<?php if ($this->type=='document' or $this->type=='article')  {?>
<td class="" colspan="2" style="height:630px">
	<div id="docmain">
	<h2 class="docul2">In construction. Will be enabled soon.</h2>
  </div>
</td>	
<?php }?>
<?php if ($this->type=='biography' or $this->type=='one_exhibition' or $this->type=='group_exhibition' or $this->type=='monograph' or $this->type=='catalog_exhibition') {?>
 <td class="" colspan="2" style="height:630px">
	<div id="docmain">
      	<div id="doctit"><?php echo $this->title?></div>
      	<?php foreach($this->itemArr as $item){ ?>
        	<div id="docsubtit"></div>
			<h3><?php //echo $item[$this->key]?>&nbsp;<?php echo html_entity_decode($item[$this->item_title], ENT_NOQUOTES, "utf-8") ?></h3>
			<ul class="docul2">
          		<li><?php echo html_entity_decode($item['contents_en'])?></li>
          		<li><?php echo html_entity_decode($item['article_summary_en'])?></li>
          		<li><?php echo html_entity_decode($item['doc_description_en'])?></li>          		
          		<?php if ($this->type=='audio' or $this->type=='video' or $this->type=='gallery' or $this->type=='article' or $this->type=='document' ) { ?>
          		<li><a href="/<?php echo $this->type?>/view-<?php echo $item[$this->key]?>">View</a></li>
          		<?php }?>
          		<?php if ($this->type=='text' ) { ?>
          		<li><a href="/<?php echo $this->type?>/<?php echo $item[$this->key]?>">View</a></li>
          		<?php }?>
	 		</ul>  
	 	<?php }?>
    </div>
  </td>
<?php }?>
<?php if ($this->type=='audio' or $this->type=='video')  {?>
<td colspan="2"><!--RELATED ITEMS DISPLAY-->
<div style="float: right;">
<div class="" id="rightBlock">
<div id="RB1"><img alt="Related Items"
	src="/images/items/tit_rel_eng.gif" /></div>
<div id="RB1Cat">
<div id="RB2"><?php
//print 'type:'.$this->type."<br>";
$langArr=$this->sess('langArr');
if ($this->relLink){
  foreach($this->relLink as $id=>$link){
    $href='/'.$this->type.'/'.$this->idStr.'_related-'.$link['type'];
    //$hrefArr[]=$href;
    ?>
<div style='z-index:100000;'
	onmouseover="MM_swapImage('ImageRB<?=$id?>','','/images/icons/tit_<?=$link['name']?>_on_<?=$langArr['lang_alt']?>.gif',1)"
	onmouseout="MM_swapImgRestore()"><a href="<?=$href?>"> <img	alt="<?=$link['title']?>" src="/images/icons/<?=$link['name']?>.gif" />
<img id="ImageRB<?=$id?>" name="ImageRB<?=$id?>"	alt="<?=$link['title']?>"	src="/images/icons/tit_<?=$link['name']?>_<?=$langArr['lang_alt']?>.gif" /></a> (<?=$link['cnt']?>)</div>
    <?php
  }
}
//print_r($hrefArr);
?><br />
<br />
</div>
<div title="" id="RB1Cat2"></div>
</div>
<div class="" id="RB1Cat3">
<div id="RB3"><!--<img src="/images/items/buy_eng.gif" alt="Related Shop Products" />-->
<div class="newCrazy1"><?=$this->l('Buy Me!')?></div>
<span class="newCrazy2"><?=$this->l('Related Shop Products')?></span>
<div id="RB4"><?php
$cnt=sizeof($this->buyItems);

for($i=0;$i<$cnt;$i++){

  $srcEnc=urlencode($this->buyItems[$i]['image_path']);
  if ($i % 3==0){
    ?>
<div class="ThumbRow clearRow"><?php
  }
  ?>
<div><a class="l11" target='_blank'
	href="http://hw-archive.com/shop/product.php?productid=<?=$this->buyItems[$i]['id']?>&cat=<?=$this->buyItems[$i]['categoryid']?>&page=1"><img
	alt="<?=$this->buyItems[$i]['descr']?>"
	src="/image/thumb/?cat=apparel&from=shop&src=<?=$srcEnc?>"><span><?=substr($this->buyItems[$i]['descr'],0,30)?></span></a></div>
  <?php
  if ($i % 3 ==2  OR $i==$num){
    ?></div>
    <?php
  }
}
?></div>
<a id="shopLink" class="l10" href="#"><?=$this->l('Visit Online Shop')?></a>
<div id="RB1Cat4"></div>
</div>
</div>
</div>
</div>
<!--MAIN ITEM DISPLAY-->
<div id="oeuvre2" title="">
<div id="inCatItems">
<img alt="<?=$this->itemProp[$this->type]['name']?>" src="/images/icons/<?=$this->itemProp[$this->type]['name']?>.gif"/>
<img alt="<?=$this->itemProp[$this->type]['name']?>" src="/images/icons/tit_<?=$this->itemProp[$this->type]['name']?>_<?=$langArr['lang_alt']?>.gif"/>
<?php
switch ($this->type) {
	case 'hwg': 
	  $inCI1_padding=80;	break;
	case 'apa': 
	  $inCI1_padding=30;	break;
	case 'arch': 
	  $inCI1_padding=45;	break;
	case 'jw': 
	  $inCI1_padding=30;	break;
	default:
		$inCI1_padding=0;
	break;
} 
?>
<div id="inCI1" style="padding-left: <?=$inCI1_padding?>px;">
</div>
	
<?php if ($this->count){

  ?> <?php foreach($this->itemArr as $n=>$item){
    //$n1=$n+1;
    //$txtIdStr=str_replace(".","_",$txtId);
    if ($item[$this->itemViewConfig['title']]){
      //$title=str_replace("\r\n","<br>",$item[$this->itemViewConfig['title']]);
      $title=html_entity_decode($item[$this->itemViewConfig['title']],ENT_QUOTES,'UTF-8');
    }else{
      //$title=str_replace("\r\n","<br>",$item[$this->itemViewConfig['title_default']]);
      $title=html_entity_decode($item[$this->itemViewConfig['title_default']],ENT_QUOTES,'UTF-8');
    }
    //                        $type,     $size='small',$id,$mode='list',$series=false,$sort='asc',$showNum=1
    $pad=true;
    if ($this->type=='gallery' or $this->type=='picture') {
      $pad=false;
    }
    $notADoc=false;
    if (!in_array($this->type,array('audio','text','video'))){
      $notADoc=true;
      if ($this->type=='gallery' or $this->type=='picture') {
        $imgPath = "/hwdb/thumbs/". html_entity_decode($item['image_path'],ENT_QUOTES,'UTF-8'); 
        if ($imgPath) {
		   $imgProps=getimagesize(DOCROOT.'/'.$imgPath);
		   $imW=$imgProps[0];
		   $imH=$imgProps[1];
		   //print "$imW,$imH<br>";
		   if ($imW>$imH){
		    if ($imW>120){
		      $imW=120;
		    }
		    $attr="width='$imW'";
		   }else{
		    if ($imH>120){
		      $imH=120;
		    }
		    $attr="height='$imH'";
		   }
        }
      } else {
        //$imgPath=$this->workImage($this->type,'small',$item[$this->itemViewConfig['image_id']],'list',true,'asc',1,$pad);
        $imgPath=$this->workImage($this->type,'small',$item[$this->itemViewConfig['id']],'list',true,'asc',1,$pad); //changed by gc
        if (!$imgPath){
          //$imgPath="/images/items/example_thumbnail.jpg";
        }
      }
    }else{
      $style='padding-left:40px;';
    }
    //print $imgPath;
    $year=$item['year'];
    if (!$year) $year=$item['publishedYear'];
    
    $idStr = $this->transId($item[$this->itemViewConfig['id']]);

    ?>
<div class="textItem0">
<div class="textItem6">
<?php if ($notADoc){?>
<a href="/<?=$this->type?>/view-<?=$idStr?>" class="newCatItem4"><img src="<?=$imgPath?>" <?=$attr?>/></a>
<?php }?>
</div>

  <?php
    if ($this->type!='paint' && in_array($this->type,$this->objectCategory['work'])){
      $objIdStr=strtoupper($this->type)." ".$item[$this->type];
      print $objIdStr."<br>";
    }
    if ($item[$this->itemViewConfig['work_number']]){
     //print "<span style='color: #595353'>".$item[$this->itemViewConfig['work_number']]."&nbsp;"."</span>";
    }
  ?>
  <a style='text-decoration:none;font-weight:bold;' href="/<?=$this->type?>/view-<?=$idStr?>"><?=$item[$this->itemViewConfig['work_number']]."&nbsp;".$title?></a>
  <?php if ($this->type=='apa') {
      echo "<br/>".$item['descriptionCategoryKeyword'].", $year";  ?> 
  <? } else {
    if ($year) echo "<br/>".$year; 
  }?> 
  <? echo "<br/>".$item['descriptionPortfolio']?>


<?php
$id=$item[$this->itemViewConfig['id']];
$quoted=false;
if (preg_match("@\D+@",$id)){
  $id="'".$id."'";
  $quoted=true;
}
?>

<div class="textItem1">
<?php
if ($this->relatedItems[$id]){

 
  foreach($this->relatedItems[$id] as $type=>$cnt){
    //print $type.'('.$cnt.'),';
    $link=$this->itemProp[$type];

    if ($quoted){
      $id=str_replace("'",'',$id);
    }
    $idStr=$this->transId($id);
    $href='/'.$this->type.'/'.$idStr.'_related-'.$type;

    ?>
    <a href="<?=$href?>"> 
    	<img alt="<?=$link['title']?>" src="/images/icons/<?=$link['name']?>.gif" class="textItem2"/>
    </a>
    <a href="<?=$href?>">
    	<img id="ImageRB<?=$id?>" name="ImageRB<?=$id?>"	alt="<?=$link['title']?>"	src="/images/icons/tit_<?=$link['name']?>_<?=$langArr['lang_alt']?>.gif" class="textItem3"/>
    </a>
    <div class="textItem4" />(<?=$cnt?>)</div>
	<?php
   }
    	
 }
?>
<div class="textItem5"></div>
</div>
</div>

<?php }?>

<div id="catPaging" class="textItem7"><!--ITEM PAGING--> 
<?php //echo $this->paginationControl($this->itemArr,'Sliding', 'item/pages.phtml');?></div>
<?php } else {
  print $this->l('No items available for this category');
}?>

</div>
</div>
</td>
<?php }?> 
</tr>