

<h4>Work Info</h4> <br/>

<table border=1 >
<tr><td>ID</td><td>  <?php echo $this->objeto_id ?></td></tr>
<tr><td>Title</td><td> <?php echo $this->titulo ?></td></tr>
<tr><td>Description</td><td>  <?php echo $this->descripcion ?></td></tr>
</table>
<br/>

<h4>Image List</h4><br/>
<table border="1"   width="900" align="center">
<tr><th>ID</th><th>Image</th><th>Name</th><th>Order</th><th>Photographer</th><th>Copyright</th><th>User</th><th>Created</th><th>Action</th></tr>
<?php 
  foreach ($this->imagenes as $imagen) {
    echo "<tr>";
    echo "<td>". $imagen['id'] . "</td>";
  	echo "<td><img src='". $this->path . $imagen['name'] . "' >"." </td>";
  	echo "<td>". $imagen['name'] . "</td>";
  	echo "<td>". $imagen['orden'] . "</td>";
  	echo "<td>". $imagen['photographer_name'] . "</td>";
  	echo "<td>". $imagen['copyright'] . "</td>";
  	echo "<td>". $imagen['user'] . "</td>";
  	echo "<td>". $imagen['created'] . "</td>";
  	echo "<td><a href='/imagen/edit?type={$this->type}&id={$this->id}&objeto_id={$this->objeto_id}&imagen_id={$imagen['id']}'> Edit </a> ";
  	echo "<br/><a href='/objeto/delete?type={$this->type}&id={$this->id}&objeto_id={$this->objeto_id}&imagen_id={$imagen['id']}'> Delete </a> </td>";
  	echo "</tr>";
  }
?>
</table>

<br/>

<a href='/imagen?n=&amp;fold=<?php echo $this->type ?>&amp;id=<?php echo $this->id ?>&amp;objeto_id=<?php echo $this->objeto_id ?>'>Add Image</a> 


<br/><br/><br/><br/><br/>