    <a name="top" id="top"></a>
    <div id="scrn-read" title="links to aid navigation for screen readers">
        [<a href="#content" accesskey="s">Skip to main content</a>] 
    </div>
    <div id="header"><img id="first" src="<?php echo $this->baseUrl(); ?>/img/rollercoaster.jpg" border="0" title="" alt="header image of a roller coaster"/><img src="<?php echo $this->baseUrl(); ?>/img/family2.jpg" border="0" title="" alt="header image of a family"/><img src="<?php echo $this->baseUrl(); ?>/img/castle.jpg" border="0" title="" alt="header image of a castle"/><img src="<?php echo $this->baseUrl(); ?>/img/family3.jpg" border="0" title="" alt="header image of a family"/>
    </div>