<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng">
<head>
    <?php echo $this->HeadMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
<!-- Israeli Web Development -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title dir="rtl">Hundertwasser</title>
<meta http-equiv="content-language" content="en" />
<meta name="author" content="Hundertwasser" />
<link rel="shortcut icon" href="images/favicon.ico" />
</head>
<body class="InBody" id="top">
<style>
body,html 
{
  padding:0;
  margin:0;
}
a 
{
text-decoration: none;
}

a:hover
{
text-decoration: underline;
}
.welcome
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #ACC790;

}
.bottom_links
{
color: #74C828;
text-decoration: none;
}
.bottom_links: hover
{
color: #74C828;
text-decoration: underline;
}

.sitemap_links
{
color: #959595;
text-decoration: none;

}
.sitemap_links : hover
{
color: #959595;
text-decoration: underline;

}

.bottom_click
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:13px;
}

.bottom
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
}

.bg
{
background-image: url(http://www.hw-archive.com/images/contact_bg.jpg);
repeat: no-repeat;
width: 1008;
height: 697;
}

.input_a
{
width:130px;
height:20px;
background: #777777;
color: #000000;
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
border-style: solid;
border-width: 1px;
border-color:#000000;
}
.input_b
{
width:380px;
height:140px;
background:#777777;
color: #000000;
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
border-style: solid;
border-width: 1px;
border-color:#000000;
}

</style>

</head>
<body>

<table cellpadding=0 cellspacing=0 align=center width=1008 height=697>
<tr>
<td class=bg valign=top>

<table cellpadding=0 cellspacing=0 align=left width=100% border=0>
  <tr><td>
  <!-- Start Top Menu -->
  <table cellpadding=0 cellspacing=0   align=left border=0>
  <tr>
  <td colspan=2 height=87></td>
  </tr>
  <tr>
  <td style="width:218px;">
  </td>
  <td>
  <table width=450 border=0><tr><td valign=top width="45" ><br style="line-height:7px;">
          <a href="home.html" onmouseover="document.home.src='http://www.hw-archive.com/images/btn_home_over.jpg'" onmouseout="document.home.src='http://www.hw-archive.com/images/btn_home.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_home.jpg" NAME="home" BORDER="0" ALT="Home"></a>
        </td>
        <td valign=top width="74"><br style="line-height:3px;">
            <a href="skins.html" onmouseover="document.skins.src='http://www.hw-archive.com/images/btn_skins_over2.gif'" onmouseout="document.skins.src='http://www.hw-archive.com/images/btn_skins2.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_skins2.gif" NAME="skins" BORDER="0" ALT="Skins"></a></td>
        <td width="84">
          <a href="shop.php" onmouseover="document.shop.src='http://www.hw-archive.com/images/btn_shop_over2.gif'" onmouseout="document.shop.src='http://www.hw-archive.com/images/btn_shop2.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_shop2.gif" NAME="shop" BORDER="0" ALT="Shop"></a>
        </td>
        <td valign=top width="85"><br style="line-height:6px;">
        <IMG SRC="http://www.hw-archive.com/images/btn_contact_over.gif" NAME="contact" BORDER="0" ALT="Contact">
        </td>
        <td valign=top>
          <a href="search.php" onmouseover="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_over2.gif'" onmouseout="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search2.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_ad_search2.gif" NAME="adsearch" BORDER="0" ALT="Advenced Search"></a>
                </td>
        </tr></table>
        <!-- End Top Menu -->
  </td></tr>
  </table>

  </td></tr>
  <tr>
  <td height=78 valign=bottom style="padding-left:35px;">
  <a href="http://www.hw-archive.com/home.html">
  <font color="#878d8a" face="Verdana" size="2"><b><u>
  Home</u></b></font></a> 
  <font color="#d45232"> <font size="1" face=verdana>&gt;</font>
  <font face="Verdana" size="2">Contact Us</font></font></td>
  </tr>
  <tr>
<td>
 <?php echo $this->layout()->content; ?>
</td>
</tr>
<tr>
<td style="padding-left:35px;">
<b><font face="Verdana" color="#959595"><br>
</font><font color="#ACC790" face="Verdana" size="2">
<br></font></b></td>
</tr>
<tr>
<td>
<br><br>
<br><br>
<table>
<tr >
<td width=35 ></td>
<td class=bottom>
<font color=577A34>All contents   &copy; 2007</font>
</td>
<td width=50 ></td>
<td class=bottom><font color=908F8F>
Design: <a target=_blank class=sitemap_links href="http://www.galordesign.com">galordesign</a> || Powered By : 
<a target=_blank class=sitemap_links href="http://www.mad-logic.com">MadLogic</a></font>
</td>
<td width=50 ></td>
<td class=bottom ><font color=908F8F>
<a class=sitemap_links href="sitemap.html">Site Map</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a  class=sitemap_links href="terms.html">Terms Of Use</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="support.html">Support</a></font>  <font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="links.html">Links</a></font>  <font color=#D8DA83>||</font><font color=908F8F>
<a class=sitemap_links href="contact.php">Contact Us</a>  </font></td>
</tr>
</table>

</td>
</tr>
</table>
</td>
</tr>
</table>

</body>
</html>
  
    