<h1><?php echo $this->escape($this->title);?></h1>
<div class="location">
<?php echo nl2br($this->escape($this->displayAddress($this->place)));?>
</div>

<h2>Reviews</h2>
<?php if(count($this->news)) : ?>
<ul id="reviews">
<?php foreach($this->news as $newsItem) : ?>
<li>
    <p class="review-meta">
        <?php echo $this->displayDate($newsItem->news_date); ?>
    </p>
    <p class="review-body"><?php echo $this->escape($newsItem->news_description); ?></p>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>