<td class="inT4" colspan="2" style="">
<div id="inT4b"
	style="background: url(images/advanced_search/top_6.jpg) left top no-repeat;">

<div class="textBox1" >
<span class="b">The art historian <span style='font-weight:normal;font-style:italic'>Pierre Restany</span> writes in his book <span style='font-weight:normal;font-style:italic'>The Power of Art, Hundertwasser, The Painter-King with the Five Skins:</span> </span> <br />
<br />
Für Hundertwasser hat der Mensch drei Häute: seine natürliche Haut, seine Kleidung, sein Haus.
Als der Künstler 1967/68 seine Nacktreden hält, um das Recht des Menschen auf seine dritte Haut geltend zu machen
(die freie Mitgestaltung seines Wohnhauses), bringt er den Verlauf der Spirale zum rituellen Abschluß:
Er findet seine erste Haut wieder, die Haut seiner ursprünglichen Wahrheit, seine Nacktheit als Mensch und Maler,
 indem er die zweite Haut (seine Kleidung) abstreift, um sein Recht auf die dritte Haut (sein Haus) zu proklamieren.
 Danach, seit 1972, als sich die große ideologische Wendung abzeichnet, wird sich die Spirale der großen Themen,
 mit denen sich Hundertwasser beschäftigt, weiter entwickeln. Seine Sensibilität für das Dasein wird durch neue Fragestellungen bereichert,
 die neue Antworten fordern und neues Engagement auslösen. Damit kommen neue Häute zur konzentrischen Einhüllung der drei erstgenannten hinzu.
  Die vierte Haut des Menschen ist sein soziales Umfeld (von der Familie bis zur Nation über die Wahlverwandtschaften des Freundeskreises).
   Die fünfte Haut ist die globale. Auf sie wirkt unmittelbar das Schicksal der Biosphäre, die Qualität der Luft, die wir atmen,
   der Zustand der Erdkruste, die uns beherbergt und ernährt.
 <br />
<br />
<?php /*?>
<span class="green">Click a skin on the image</span><span class="orange">
to view the skin's related texts >></span>
<?*/?>
</div>

</div>

</td>
