<td colspan="2"><!--RELATED ITEMS DISPLAY-->
<div style="float: right;">
<div class="" id="rightBlock">
<div id="RB1"><img alt="Related Items"
	src="/images/items/tit_rel_eng.gif" /></div>
<div id="RB1Cat">
<div id="RB2"><?php
//print 'type:'.$this->type."<br>";
$langArr=$this->sess('langArr');
if ($this->relLink){
  foreach($this->relLink as $id=>$link){
    $href='/'.$this->type.'/'.$this->idStr.'_related-'.$link['type'];
    //$hrefArr[]=$href;
    ?>
<div style='z-index:100000;'
	onmouseover="MM_swapImage('ImageRB<?=$id?>','','/images/icons/tit_<?=$link['name']?>_on_<?=$langArr['lang_alt']?>.gif',1)"
	onmouseout="MM_swapImgRestore()"><a href="<?=$href?>"> <img	alt="<?=$link['title']?>" src="/images/icons/<?=$link['name']?>.gif" />
<img id="ImageRB<?=$id?>" name="ImageRB<?=$id?>"	alt="<?=$link['title']?>"	src="/images/icons/tit_<?=$link['name']?>_<?=$langArr['lang_alt']?>.gif" /></a> (<?=$link['cnt']?>)</div>
    <?php
  }
}
//print_r($hrefArr);
?> <br />
<br />
 </div>
<div title="" id="RB1Cat2"></div>
</div>
<div class="" id="RB1Cat3">
<div id="RB3"><!--<img src="/images/items/buy_eng.gif" alt="Related Shop Products" />-->
<div class="newCrazy1"><?=$this->l('Buy Me!')?></div>
<span class="newCrazy2"><?=$this->l('Related Shop Products')?></span>
<div id="RB4"><?php
$cnt=sizeof($this->buyItems);

for($i=0;$i<$cnt;$i++){

  $srcEnc=urlencode($this->buyItems[$i]['image_path']);
  if ($i % 3==0){
    ?>
<div class="ThumbRow clearRow"><?php
  }
  ?>
<div><a class="l11" target='_blank'
	href="http://hw-archive.com/shop/product.php?productid=<?=$this->buyItems[$i]['id']?>&cat=<?=$this->buyItems[$i]['categoryid']?>&page=1"><img
	alt="<?=$this->buyItems[$i]['descr']?>"
	src="/image/thumb/?cat=apparel&from=shop&src=<?=$srcEnc?>"><span><?=substr($this->buyItems[$i]['descr'],0,30)?></span></a></div>
  <?php
  if ($i % 3 ==2  OR $i==$num){
    ?></div>
    <?php
  }
}
?></div>
<a id="shopLink" class="l10" href="#"><?=$this->l('Visit Online Shop')?></a>
<div id="RB1Cat4"> </div>
</div>
</div>
</div>
</div>
<!--MAIN ITEM DISPLAY-->
<div>
<div id="inCatItems" style="background:url(/images/items/top_6b.jpg) left top no-repeat;">
<img alt="Paintings" src="/images/icons/<?=$this->itemProp[$this->type]['name']?>.gif"/>
<img alt="Paintings" src="/images/icons/tit_<?=$this->itemProp[$this->type]['name']?>_<?=$langArr['lang_alt']?>.gif"/>
<div id="inCI1">
(<?=$this->fromStr?> - <?=$this->toStr?> of <?=$this->count?>)
<?php if (in_array($this->type,$this->objectCategory['work'])){
$fItem=$this->itemArr->getItem(1);
$idStr=$this->transId($fItem[$this->itemViewConfig['id']]);
  ?>
<a class="l4" href="/<?=$this->type?>/slides-<?=$idStr?>">View Slideshow</a>
<?php }?>
</div>
<?php if ($this->count){

  ?> <?php foreach($this->itemArr as $n=>$item){
    //$n1=$n+1;
    //$txtIdStr=str_replace(".","_",$txtId);
    if ($item[$this->itemViewConfig['title']]){
      //$title=str_replace("\r\n","<br>",$item[$this->itemViewConfig['title']]);
      $title=html_entity_decode($item[$this->itemViewConfig['title']],ENT_QUOTES,'UTF-8');
    }else{
      //$title=str_replace("\r\n","<br>",$item[$this->itemViewConfig['title_default']]);
      $title=html_entity_decode($item[$this->itemViewConfig['title_default']],ENT_QUOTES,'UTF-8');
    }
    //                        $type,     $size='small',$id,$mode='list',$series=false,$sort='asc',$showNum=1
    $pad=true;
    if ($this->type=='gallery'){
      $pad=false;
    }
    $notADoc=false;
    if (!in_array($this->type,array('audio','text','video'))){
      $notADoc=true;

      $imgPath=$this->workImage($this->type,'small',$item[$this->itemViewConfig['image_id']],'list',true,'asc',1,$pad);
      if (!$imgPath){
        $imgPath="/images/items/example_thumbnail.jpg";
      }
    }else{
      $style='padding-left:40px;';
    }
    //print $imgPath;
    if ($year=$item['year']){
      $year='<br />'.$year;
    }
    $idStr=$this->transId($item[$this->itemViewConfig['id']]);

    ?>
<div class="CatItem1" style='margin-bottom:40px;'>
<?php if ($notADoc){?>
<div class="CatItem2"><a href="/<?=$this->type?>/view-<?=$idStr?>"><img src="<?=$imgPath?>" /></a></div>
<?php }?>
<div style='<?=$style?>' title="" class="CatItem3">
<div style=''>
  <?php
    if ($this->type!='paint' && in_array($this->type,$this->objectCategory['work'])){
      $objIdStr=strtoupper($this->type)." ".$item[$this->type];
      print $objIdStr."<br>";
    }
    if ($item[$this->itemViewConfig['work_number']]){
     print $item[$this->itemViewConfig['work_number']];
    }
  ?>
  <span><a style='text-decoration:none;' href="/<?=$this->type?>/view-<?=$idStr?>"><?=$title?></a></span>
  <?=$year?>
</div>

<?php
$id=$item[$this->itemViewConfig['id']];
$quoted=false;
if (preg_match("@\D+@",$id)){
  $id="'".$id."'";
  $quoted=true;
}

if ($this->relatedItems[$id]){

  foreach($this->relatedItems[$id] as $type=>$cnt){
    //print $type.'('.$cnt.'),';
    $link=$this->itemProp[$type];

    if ($quoted){
      $id=str_replace("'",'',$id);
    }
    $idStr=$this->transId($id);
    $href='/'.$this->type.'/'.$idStr.'_related-'.$type;

    ?>
    <a href="<?=$href?>"> <img	alt="<?=$link['title']?>" width='24px' src="/images/icons/<?=$link['name']?>.gif" />
<img id="ImageRB<?=$id?>" height='15px' name="ImageRB<?=$id?>"	alt="<?=$link['title']?>"	src="/images/icons/tit_<?=$link['name']?>_<?=$langArr['lang_alt']?>.gif" /></a><span style='padding-bottom:3px;font-size:12px;'>(<?=$cnt?>)</span>
    <?php

  }
}
?>

</div>
<div class="CatItem4" /></div>
</div>

    <?php }?>

<div id="catPaging" style='float: left;'><!--ITEM PAGING--> <?php
echo $this->paginationControl($this->itemArr,'Sliding', 'skin/pages.phtml');
?></div>
<?php }else{
  print $this->l('No items available for this category');
}?></div>
</div>

</td>
