<?php
$title=$this->item['title'.$this->langArr['lang_word']];
if (!$title){
  $title=$this->item['title'];
}
if($workNumStr=$this->item['workNumber']){
  $workNumStr.="&nbsp;";
}
?>

<!--<table cellpadding="2" cellspacing="2">
<tr style='font-weight:bold;'>
<td>ARCH</td>
<td>&nbsp;<?=$this->item['arch']?></td>
</tr>
<tr>
<td><h2><?=$workNumStr?></h2></td>
<td><h2><?=$title?></h2></td>
</tr>
</table>
<br/>
-->
ARCH <?=$this->item['arch']?>
<br/><h2><?=$workNumStr.$title?></h2>
<?php
print showTitle($this->item['titleEnglish'],$title);
print showTitle($this->item['titleGerman'],$title);
print showTitle($this->item['titleFrench'],$title);
print showTitle($this->item['titleItalian'],$title);
print showTitle($this->item['titleSpanish'],$title);
print showTitle($this->item['titleJapanese'],$title);
?>
<br/>
<div class="itemView2">
<?=showProp($this->item['descriptionCategoryKeyword'])?>
<?=showProp($this->item['street'],'',false,', ').showProp($this->item['zip'],'',false,', ').showProp($this->item['place'],'',false,', ').showProp($this->item['country'])?>
<?=showProp($this->item['constructionStart'],'',false,' - ').showProp($this->item['constructionFinished'])?>
<?=showProp($this->item['description'])?>
<? if ($this->item['finishedPlace']) { echo showProp($this->item['finishedPlace'],'',false,', ').showProp($this->item['year']); }?>
<?=showProp($this->item['heightMm'],'',false,' mm x ').showProp($this->item['widthMm'],'',true,' mm')?>
<?=showProp($this->item['widthCm'],'',false,' cm x ').showProp($this->item['depthCm'],'',false,' cm x ').showProp($this->item['heigthCm'],'',true,' cm')?>
<?=showProp($this->item['technique'])?>
<?=showProp($this->item['developer'],$this->l('Developer'))?>
<?=showProp($this->item['planning'],$this->l('Planning'))?>
<?=showProp($this->item['executedBy '],$this->l('Executed by'))?>
<?=showProp($this->item['date'],$this->l('Date'))?>
<?=showProp($this->item['notRealised'])?>
<?=showProp(getCountryName($this->item['country']),$this->l('Country'))?>
</div>

<div class="text1">
	<?php
	showText($this->item['hundertwasser_comment_'.$this->langArr['lang_alt_short']],
          	$this->item['hundertwasser_comment_ge'],
          	$this->langArr['lang_alt_short'],
          	          'ge',
          	$this->l('Hundertwasser comment about the work'),'font-size:15px;');

	showText($this->item['information_'.$this->langArr['lang_alt_short']],
        	$this->item['information_ge'],
        	$this->langArr['lang_alt_short'],
        	          'ge',
        	$this->l(''),'font-size:15px;');

?>
  <?php $this->showList($this->item['oneManExhibitions'],$this->l('One-man exhibitions'))?>

	<?php $this->showList($this->item['groupExhibitions'],$this->l('Group Exhibitions'))?>

	<?php $this->showList($this->item['literatureMonographs'],$this->l('Literature'),$this->l('Monographs'))?>

	<?php $this->showList($this->item['literatureExhibitionCatalogues'],$this->l('Literature'),$this->l('Exhibition Catalogues'))?>

	<?php $this->showList($this->item['literatureVarious'],$this->l('Literature'),$this->l('Various'))?>

  <?php $this->showList($this->item['literatureMagazinesPeriodicals'],$this->l('Literature'),$this->l('Magazines/Periodicals'))?>
  <?php $this->showList($this->item['reproductionsArtPrints'],$this->l('Reproductions Art prints'))?>




</div>

<?php
	function showTitle($titleLang,$title){
	  if ($titleLang && $titleLang!=$title){
	   ?>
	   
      <h2><?=$titleLang?></h2>

	   <?php
	  }
	}

function showProp($val,$lab='',$br=true,$extra=''){
  if ($val){
    $brTag='';
    if ($br){
      $brTag="<br />";
    }
    if ($lab){
      $lab1=$lab.': ';
    }
    //return $lab1.$val.$extra.$brTag;
    return $lab1.html_entity_decode($val, ENT_QUOTES, "utf-8").$extra.$brTag;
  }
}

function showText($textLang, $textDef, $curLang, $defLanguage,$header){
  $res=$textLang;
	if (!$res && $curLang!=$defLanguage){
	  $res=$textDef;
	}
	if ($res){
	?>
	<?php if ($header) {?><br><span class="t1"><?=$header?></span>:<?php }?>
	<br><?php echo html_entity_decode($res, ENT_QUOTES, "utf-8") ; ?><br/>
<?php
	 }

}



function showList($val,$header1,$header2=''){
  if (isset($val)){
    ?>
<br>
<span class="t1"><?=$header1?></span>:<? if ($header2) print $header2;?>
<ul class="ul1">
<?php
$arr=explode("<br>",$val);
foreach($arr as $rn=>$row){
  ?>
	<li><?=$row?></li>
	<?php
}
?>
</ul>
<?php
  }
}


function getCountryName($code) {
  
  switch ($code) {
    case A:
  	  return "Austria";
  	break;
    
  	case D:
  	  return "Germany";
  	break;
    
  	case J:
  	  return "Japan";
  	break;
  	case NL:
  	  return "Netherlands";
  	break;
  	case CH:
  	  return "Switzerland";
  	break;
  	case NZ:
  	  return "New Zealand";
  	break;  	  	
  	
  	default:
  	return $code;
  	break;
  }
  
}
?>