<br>
<h2><?php
$title=$this->item['gallery_title_'.$this->langArr['lang']];
if (!$title){
  $title=$this->item['gallery_title_en'];
}
print $title;
?></h2>
<div class="itemView2">

<?=showProp($this->item["gallery_description_{$this->langArr['lang']}"])?>
<?=showProp($this->item["galery_place_{$this->langArr['lang']}"])?>
<?=showProp($this->item["gallery_year"])?>
<?=showProp($this->item["gallery_year_circa"])?>
<?=showProp($this->item["gallery_photographer"],$this->l('Photographer'))?>
<?=showProp($this->item["gallery_copyright"], $this->l('Copyright'))?>
</div>

<?php
function showProp($val,$lab=''){
  if ($val){
    if ($lab){
      $lab1=$lab.': ';
    }
    return $lab1.html_entity_decode($val,ENT_QUOTES,'UTF-8').'<br>';
  }
}
?>
