<?php
$title=$this->item['title'.$this->langArr['lang_word']];
if (!$title){
  $title=$this->item['title'];
}
if($workNumStr=$this->item['workNumber']){
  $workNumStr=$workNumStr."&nbsp;&nbsp;&nbsp;";
}
?>


JW&nbsp;<?=$this->item['jw']?>
<br/><h2><?=$workNumStr.$title?></h2>
<?php
print showTitle($this->item['titleEnglish'],$title);
print showTitle($this->item['titleGerman'],$title);
print showTitle($this->item['titleFrench'],$title);
print showTitle($this->item['titleItalian'],$title);
print showTitle($this->item['titleSpanish'],$title);
print showTitle($this->item['titleJapanese'],$title);
?>
<br/>

<div class="itemView2">
<? echo showProp($this->item['finishedPlace'] .", ". $this->item['year'])?>
<?=showProp($this->item['technique'])?>
<?=showProp($this->item['heightMm'],'',false,' cm x ').showProp($this->item['widthMm'],'',true,' cm')?>
<?=showProp($this->item['date'])?>
</div>

<div class="text1">
	<?php
	showText($this->item['hundertwasser_comment_'.$this->langArr['lang_alt_short']],
          	$this->item['hundertwasser_comment_ge'],
          	$this->langArr['lang_alt_short'],
          	          'ge',
          	$this->l('Hundertwasser comment about the work'),'font-size:15px;');

	showText($this->item['information_'.$this->langArr['lang_alt_short']],
        	$this->item['information_ge'],
        	$this->langArr['lang_alt_short'],
        	          'ge',
        	$this->l(''),'font-size:15px;');

?>
  <?php $this->showList($this->item['oneManExhibitions'],$this->l('One-man exhibitions'))?>

	<?php $this->showList($this->item['groupExhibitions'],$this->l('Group Exhibitions'))?>

	<?php $this->showList($this->item['literatureMonographs'],$this->l('Literature'),$this->l('Monographs'))?>

	<?php $this->showList($this->item['literatureExhibitionCatalogues'],$this->l('Literature'),$this->l('Exhibition Catalogues'))?>

  <?php $this->showList($this->item['literatureVarious'],$this->l('Literature'),$this->l('Various'))?>

  <?php $this->showList($this->item['literatureMagazinesPeriodicals'],$this->l('Literature'),$this->l('Magazines/Periodicals'))?>

  <?php $this->showList($this->item['reproductionsArtPrints'],$this->l('Reproductions Art prints'))?>

</div>

<?php

function showProp($val,$lab='',$br=true,$extra=''){
  if ($val){
    $brTag='';
    if ($br){
      $brTag="<br />";
    }
    if ($lab){
      $lab1=$lab.': ';
    }
    return $lab1.$val.$extra.$brTag;
  }
}
function showTitle($titleLang,$title){
  if ($titleLang && $titleLang!=$title){
   ?>
	<h2><?=$titleLang?></h2>
   <?php
  }
}

function showText($textLang, $textDef, $curLang, $defLanguage,$header){
  $res=$textLang;
	if (!$res && $curLang!=$defLanguage){
	  $res=$textDef;
	}
	if ($res){
	?>
	<?php if ($header) {?><br><span class="t1"><?=$header?></span>:<?php }?>
	<br><?php echo html_entity_decode($res, ENT_QUOTES, "utf-8") ; ?><br/>
<?php
	 }

}



function showList($val,$header1,$header2=''){
  if (isset($val)){
    ?>
<br>
<span class="t1"><?=$header1?></span>:<? if ($header2) print $header2;?>
<ul class="ul1">
<?php
$arr=explode("<br>",$val);
foreach($arr as $rn=>$row){
  ?>
	<li><?=$row?></li>
	<?php
}
?>
</ul>
<?php
  }
}

?>
