<div class="f1">All content &copy; 2009</div>
<div class="f2">
	Design: <a href="http://www.galordesign.com" class="l2">Galordesign</a> |&nbsp;| Powered By: <a href="http://www.mad-logic.com" class="l2">Madlogic</a>
</div>

<div class="f3">
	<a href="/" class="l3">Home Page</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Site Map</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Terms Of Use</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Support</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;

	<a href="#" class="l3">Links</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="/contact" class="l3">Contact Us</a>
</div>