<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng">
<head>
<!-- Israeli Web Development -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title dir="rtl">Hundertwasser</title>
<meta http-equiv="content-language" content="en" />
<meta name="author" content="Hundertwasser" />
<link rel="shortcut icon" href="images/favicon.ico" />
</head>
<body class="InBody" id="top">
<style>
body,html 
{
  padding:0;
  margin:0;
}
a 
{
text-decoration: none;
}

a:hover
{
text-decoration: underline;
}
.welcome
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #ACC790;

}
.bottom_links
{
color: #74C828;
text-decoration: none;
}
.bottom_links: hover
{
color: #74C828;
text-decoration: underline;
}

.sitemap_links
{
color: #959595;
text-decoration: none;

}
.sitemap_links : hover
{
color: #959595;
text-decoration: underline;

}

.bottom_click
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:13px;
}

.bottom
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
}

.bg
{
background-image: url(http://www.hw-archive.com/images/skins_bg.jpg);
repeat: no-repeat;
width: 1008;
height: 796;
}
</style>
</head>
<body >
<table cellpadding=0 cellspacing=0 align=center width=1008 height=796>
<tr>
<td align=center class=bg valign=top>
  <table cellpadding=0 cellspacing=0 align=left><tr><td>
  

  <!-- Start Top Menu -->
  <table cellpadding=0 cellspacing=0   align=left>
  <tr>
  <td colspan=2 height=87></td>
  </tr>
  <tr>
  <td style="width:218px;">
  </td>
  <td>
  <table width=450><tr><td valign=top width="45"><br style="line-height:7px;">
          <a href="/" onmouseover="document.home.src='http://www.hw-archive.com/images/btn_home_over.jpg'" onmouseout="document.home.src='http://www.hw-archive.com/images/btn_home.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_home.jpg" NAME="home" BORDER="0" ALT="Home"></a>
        </td>
        <td valign=top width="74"><img src="http://www.hw-archive.com/images/btn_skins2_ge.gif"></td>
        <td width="84">
          <a href="/shop/home.php" onmouseover="document.shop.src='http://www.hw-archive.com/images/btn_shop_over.jpg'" onmouseout="document.shop.src='http://www.hw-archive.com/images/btn_shop.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_shop.jpg" NAME="shop" BORDER="0" ALT="Shop"></a>
        </td>
        <td valign=top width="85"><br style="line-height:6px;">
          <a href="/contact" onmouseover="document.contact.src='http://www.hw-archive.com/images/btn_contact_over_ge.gif'" onmouseout="document.contact.src='http://www.hw-archive.com/images/btn_contact_ge.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_contact_ge.gif" NAME="contact" BORDER="0" ALT="Kontakt"></a>
        </td>
        <td valign=top>
          <a href="/search" onmouseover="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_over_ge.gif'" onmouseout="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_ge.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_ad_search_ge.gif" NAME="adsearch" BORDER="0" ALT="Spezial recherche"></a>
        </td>
        </tr></table>
        <!-- End Top Menu -->
  </td></tr>
  </table>
  
</td></tr>
<tr>
<td valign=top width=1008>
<table width="1006">
<tr><td width=35></td>
<td width=500 valign=top class=welcome align=left>
<br style="line-height:75px;">
<a href=""><font color=878D8A><b><u>Home</u></b></font></a><font color=878D8A> <font color="D45232">>Skins</font>
<br>
<br style="line-height:50px;">
<font color=#7CC433 size="2"><b>What are Hundertwasser skins ?</b></font>
<br>
<br style="line-height:18px;">
</font><font color=#97AF86> <span style="vertical-align: super">
<b>Here Comes a short description of the Hundertwasser<br>
skins Here Comes of the Hundertwasser skins. </b>
</span>
<br>
<br style="line-height:18px;">
<span style="vertical-align: super"><b>Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Hundertwasser skins </b></span>

<br>
<br style="line-height:18px;">
<span style="vertical-align: super"><b>Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Description of the Hundertwasser skinsHere Comes a short<br>
the Hundertwasser skinsHere Comes a shortHere Comes<br>
Hundertwasser skins </b></span>

</td>
<td valign=top align=left>
     <object
        classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
        codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,79,0"
        id="skins"
        width="433" height="577"
      >
        <param name="movie" value="/flash/skins.swf">
        <param name="bgcolor" value="#000000">
        <param name="quality" value="high">
        <param name="allowscriptaccess" value="samedomain">
        <embed
          type="application/x-shockwave-flash"
          pluginspage="http://www.macromedia.com/go/getflashplayer"
          name="skins"
          width="433" height="577"
          src="/flash/skins.swf"
          bgcolor="#000000"
          quality="high"
          swliveconnect="true"
          allowscriptaccess="samedomain"
        >
          <noembed>
          </noembed>
        </embed>
      </object>
</td>
</tr>
</table>

</td>
</tr>
<tr>
<td valign=top width=1008>
<table>
<tr><td width=35></td>
<td class=welcome width=1008 valign=top align=left>
<b><font color="D45232">Click a skin on the image</font> 
<font color="83B238">to view the skin's related Hundertwasser texts >>
</font></b>
</td>
</tr>
</table>
<br>
</td>
</tr>
<tr>
<td align=left bgcolor=#000000>
<table bgcolor=#000000 height=50>
<tr >
<td width=35 bgcolor=#000000></td>
<td class=bottom bgcolor=#000000>
<font color=577A34>All contents   &copy; 2007</font>
</td>
<td width=50 bgcolor=#000000></td>
<td class=bottom><font color=908F8F>
Design: <a target=_blank class=sitemap_links href="http://www.galordesign.com">galordesign</a> || Powered By : 
<a target=_blank class=sitemap_links href="http://www.mad-logic.com">MadLogic</a></font>
</td>
<td width=50 bgcolor=#000000></td>
<td class=bottom bgcolor=#000000><font color=908F8F>
<a class=sitemap_links href="sitemap.html">Site Map</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a  class=sitemap_links href="terms.html">Terms Of Use</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="support.html">Support</a></font>  <font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="links.html">Links</a></font>  <font color=#D8DA83>||</font><font color=908F8F>
<a class=sitemap_links href="/contact">Contact Us</a>  </font></td>
</tr>
</table>
</td>
</tr>

</table>





</td>
</tr>
</table>

</body>
</html>
  
    