<!--Hundertwasser-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<?php echo $this->HeadMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php print $this->headScript();?>
<meta name="description" content="Hudertwasser skins paintings architecture video applied art graphics" />
<link rel="shortcut icon" href="images/favicon.ico" />
</head>
<body>
<table class="tab1">
	<tr>
		<td  class="tab1TD1"><!--   FLASH   -->
			<div id="mainf" class="">
				<div id="flashcontent1">
					<br />
					<br />
					Your browser does not support Flash technology.<br /><span>To install Flash Player
					<a href="http://get.adobe.com/flashplayer/" class="l4" >
						click here
					</a>.
					<br /></span>
				</div>
				<script type="text/javascript">
				var so = new SWFObject("images/main.swf", "mySwfID1", "507", "530", "8", "#Ffffff");
				so.addParam("scale", "noborder");
				so.addParam("salign", "tl");
				so.addParam("wmode", "transparent");
				so.write("flashcontent1");
				</script>
			</div>

		</td>
	</tr>
	<tr>
		<td  class="tab1TD2">
		<img src="images/trans.gif" width="800" height="1" alt="hundertwasser" />
			<div class="hpT1"><!--   TEXT 1   -->
				<b>In</b> Hundertwasser finden wir den verantwortungsbewußten und visionären Künstler, der die aufklärerische Kraft seiner Kunst dafür einsetzt, die Botschaft eines Lebens in Harmonie mit der Natur und der individuellen Kreativität zu verbreiten.
				 <br /><br />Er ist Symbolfigur einer non-konformistischen Lebensweise,
				<br /><img src="images/trans.gif" width="1" height="185" alt="hundertwasser"/>
			</div>
			<div class="hpT2"><!--   TEXT 2   -->
			ein Vorläufer der Umweltbewegung und Botschafter einer selbstbestimmten alternativen Existenz. <br /><br />

<b>E</b>ntdecken Sie an Hand des Symbols der 5 Häute Hundertwassers Welt, seine Visionen, seine Ideale und seine Botschaften
Das Werk – Hundertwassers Catalogue Raisonné


			</div>
			<div class="hpT3"><!--   NEWS REEL   -->
				Here comes the news ticker
				text which includes events, news
				&amp; current announcments to a maximum size represented
				By this short text.
				The news items will switch.
			</div>
			<div id="top1">
				<div id="top1_1"><!--   LANGUAGES   -->
					<a href="#"><img src="images/flag_fr.gif" alt="French" /></a>
					<a href="#"><img src="images/flag_ger.gif" alt="German" /></a>
					<div><img src="images/eng.jpg" alt="English" /></div>
				</div>
				<div id="top1_2"><!--   SEARCH   -->
					<form action="#" name="hpSeacrh" id="hpSeacrh" method="post">
						<div class="top1_2a">
							<input name="someName" type="text" class="input1" />
						</div>
						<div class="top1_2b">
							<div onClick="javascript:document.hpSeacrh.submit();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image1','','images/btn_search_over.gif',1)">
							 	<img src="images/btn_search.gif" alt="Quick Search" name="Image1" id="Image1" />
							 </div>
						</div>
					</form>
				</div>
				<div id="top1_3" title=""><img src="images/logo1.gif" alt="Hundertwasser" /></div><!--   LOGO   -->
				<div id="top1_4" title=""><!--   SKINS   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image2','','images/btn_skins_over.gif',1)">
						<a href="/skin"><img  src="images/btn_skins.gif" alt="Skins" name="Image2" id="Image2" /></a>
					 </div>
				</div>
				<div id="top1_8" title=""><!--   OUEVRE   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image6','','images/btn_ouevre_over.gif',1)">
						<a href="/oeuvre"><img  src="images/btn_ouevre.gif" alt="The Ouevre" name="Image6" id="Image6" /></a>
					 </div>
				</div>
				<div id="top1_5" title=""><!--   SHOP   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image3','','images/btn_shop_over.jpg',1)">
						<a href="#"><img  src="images/btn_shop.jpg" alt="Shop" name="Image3" id="Image3" /></a>
					 </div>
				</div>
				<div id="top1_6" title=""><!--   CONTACT US   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image4','','images/btn_contact_over.gif',1)">
						<a href="contact.php"><img  src="images/btn_contact.gif" alt="Contact Us" name="Image4" id="Image4" /></a>
					 </div>
				</div>
				<div id="top1_7" title=""><!--   ADVANCED SEARCH   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image5','','images/btn_advanced_over.gif',1)">
						<a href="advanced_search.php"><img  src="images/btn_advanced.gif" alt="Advanced Search" name="Image5" id="Image5" /></a>
					 </div>
				</div>
			</div>
		</td>
	</tr>
	<tr>
		<td  class="footer"><!--   FOOTER   -->
			<div class="f1">All content &copy; 2009</div>
<div class="f2">
	Design: <a href="http://www.galordesign.com" class="l2">Galordesign</a> |&nbsp;| Powered By: <a href="http://www.mad-logic.com" class="l2">Madlogic</a>
</div>
<div class="f3">
	<a href="index.php" class="l3">Home Page</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Site Map</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Terms Of Use</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Support</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Links</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="contact.php" class="l3">Contact Us</a>
</div>		</td>
	</tr>
</table>
</body>
</html>
