<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng">
<head>
<!-- Israeli Web Development -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title dir="rtl">Hundertwasser</title>
<meta http-equiv="content-language" content="en" />
<meta name="author" content="Hundertwasser" />
<link rel="shortcut icon" href="images/favicon.ico" />
</head>
<body class="InBody" id="top">
<style>
body,html 
{
  padding:0;
  margin:0;
}
a 
{
text-decoration: none;
}

a:hover
{
text-decoration: underline;
}
.welcome
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #ACC790;

}
.bottom_links
{
color: #74C828;
text-decoration: none;
}
.bottom_links: hover
{
color: #74C828;
text-decoration: underline;
}

.sitemap_links
{
color: #959595;
text-decoration: none;

}
.sitemap_links : hover
{
color: #959595;
text-decoration: underline;

}

.bottom_click
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:13px;
}

.bottom
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
}

.bg
{
background-image: url(http://www.hw-archive.com/images/search_bg.jpg);
repeat: no-repeat;
width: 1008;
height: 1024;
}

.input_a
{
width:80px;
height:10px;
background:#65A31B;
color: #000000;
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
border-style: solid;
border-width: 1px;
border-color:#000000;
}
.input_b
{
width:60px;
height:10px;
background:#65A31B;
color: #000000;
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
border-style: solid;
border-width: 1px;
border-color:#000000;
}

</style>
</head>
<body >
<table cellpadding=0 cellspacing=0 align=center width=1008 height=868>
<tr>
<td align=center class=bg valign=top>
  <table cellpadding=0 cellspacing=0 align=left><tr><td>
  

  <!-- Start Top Menu -->
  <table cellpadding=0 cellspacing=0   align=left>
  <tr>
  <td colspan=2 height=87></td>
  </tr>
  <tr>
  <td style="width:218px;">
  </td>
  <td>
  <table width=450><tr><td valign=top width="45"><br style="line-height:7px;">
          <a href="/" onmouseover="document.home.src='http://www.hw-archive.com/images/btn_home_over.jpg'" onmouseout="document.home.src='http://www.hw-archive.com/images/btn_home.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_home.jpg" NAME="home" BORDER="0" ALT="Home"></a>
        </td>
        <td valign=top width="74"><a href="/skin"><img src="http://www.hw-archive.com/images/btn_skins2_ge.gif" border=0></img></a></td>
        <td width="84">
          <a href="shop/home.php" onmouseover="document.shop.src='http://www.hw-archive.com/images/btn_shop_over.jpg'" onmouseout="document.shop.src='http://www.hw-archive.com/images/btn_shop.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_shop.jpg" NAME="shop" BORDER="0" ALT="Shop"></a>
        </td>
        <td valign=top width="85"><br style="line-height:6px;">
          <a href="/contact" onmouseover="document.contact.src='http://www.hw-archive.com/images/btn_contact_over_ge.gif'" onmouseout="document.contact.src='http://www.hw-archive.com/images/btn_contact_ge.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_contact_ge.gif" NAME="contact" BORDER="0" ALT="Kontakt"></a>
        </td>
        <td valign=top>
          <a href="/search" onmouseover="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_over_ge.gif'" onmouseout="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_ge.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_ad_search_ge.gif" NAME="adsearch" BORDER="0" ALT="Spezial recherche"></a>
        </td>
        </tr></table>
        <!-- End Top Menu -->
  </td></tr>
  </table>
  
</td></tr>
<tr>
<td valign=top width=1008>

<?php echo $this->layout()->content; ?>
</td>
</tr>
</table>
</body>
</html>
  
    