<div id="skins_flash"><!--SKINS FLASH-->

<div id="skins_flash2">
<div id="flashcontent1"><br />
<br />
Your browser does not support Flash technology.<br />
<span>To install Flash Player <a
	href="http://get.adobe.com/flashplayer/" class="l4"> click here </a>. <br />
</span></div>

<script type="text/javascript">
					var so = new SWFObject("images/skins/skins.swf", "mySwfID1", "435", "580", "8", "#Ffffff");
					so.addParam("scale", "noborder");
					so.addParam("salign", "tl");
					so.addParam("wmode", "transparent");
					so.write("flashcontent1");
					</script></div>
</div>