	<!--BREADCRUMB PATH-->
	<tr>
		<td class="" style="height: 136px; background: url(&quot;images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;">
			<div id="bcPath">
				<a href="/" class="l4 b">Home Page</a> &gt;
				<span class="l4on">The Oeuvre</span>
			</div>
		</td>
		<td>
			<div class="bcPath3" title="" style="background: url(&quot;images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">&nbsp;</div>
		</td>
	</tr>
	<tr>
<td class="" colspan="2" style="height:630px"><!--CATEGORY LIST-->
              <div id="inContact" title="" style="background:url(/images/advanced_search/top_6b.jpg) left top no-repeat;">
				<div id="oeuvre1">
					<div id="onBtn_1" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB1','','/images/oeuvre/btn_early_work_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=jw">
							<img src="/images/oeuvre/btn_early_work_eng.gif" alt="Early Works"  name="ImageRB1" id="ImageRB1" />

						</a>
					</div>			
					<div id="onBtn_2"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB2','','/images/oeuvre/btn_paintings_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=paint">
							<img src="/images/oeuvre/btn_paintings_eng.gif" alt="Paintings"  name="ImageRB2" id="ImageRB2" />
						</a>
					</div>
					<div id="onBtn_3"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB3','','/images/oeuvre/btn_original_graphic_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=hwg">
							<img src="/images/oeuvre/btn_original_graphic_eng.gif" alt="Original Graphic"  name="ImageRB3" id="ImageRB3" />
						</a>
					</div>
					<div id="onBtn_4"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB4','','/images/oeuvre/btn_tapestry_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=tap">
							<img src="/images/oeuvre/btn_tapestry_eng.gif" alt="Tapestry" name="ImageRB4" id="ImageRB4" />
						</a>
					</div>
					<div id="onBtn_5"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB5','','/images/oeuvre/btn_apa_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=apa">
							<img src="/images/oeuvre/btn_apa_eng.gif" alt="Applied Art" name="ImageRB5" id="ImageRB5" />
						</a>
					</div>
					<div id="onBtn_6"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB6','','/images/oeuvre/btn_architecture_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=arch">
							<img src="/images/oeuvre/btn_architecture_eng.gif" alt="Architecture" name="ImageRB6" id="ImageRB6" />
						</a>
					</div>

					<?php 
					/*
					?>					
					<div id="oBtn_7"  onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('ImageRB9','','/images/oeuvre/btn_documentation_on_eng.gif',1)">
						<a href="/item/object-list/?type[]=text">
							<img src="/images/oeuvre/btn_documentation_eng.gif" alt="Documentation" name="ImageRB9" id="ImageRB9" />
						</a>
					</div>	
					<? 
					*/
					?>
				</div>		
			</div>
</td>
</tr>