<br>
<h2><?php
$title=$this->item['title_'.$this->langArr['lang']];
if (!$title){
  $title=$this->item['title'];
}
print $title;
?></h2>
<div class="itemView2">
<?=showProp($this->item['subtitle_'.$this->langArr['lang']])?>
<?=showProp($this->item['author_'.$this->langArr['lang']],$this->l('Author'))?>
<?=showProp($this->item['director_'.$this->langArr['lang']],$this->l('Director'))?>
<?=showProp($this->item['producer_'.$this->langArr['lang']],$this->l('Producer'))?>
<?=showProp($this->item['date_of_shot'])?>
<?=showProp($this->item['year_of_shot'])?>
<?=showProp($this->item['place_of_shot_'.$this->langArr['lang']])?>
<?=showProp($this->item['duration'])?>
<?=showProp($this->item['bc_title_'.$this->langArr['lang']])?>
<?=showProp($this->item['bc_date'])?>
<?=showProp($this->item['bc_year'])?>
<?=showProp($this->item['bc_time'])?>
<?=showProp($this->item['bc_place_'.$this->langArr['lang']])?>
<?=showProp($this->item['bc_company_'.$this->langArr['lang']])?>
<?=showProp($this->item['language'])?>
<?=showProp($this->item['content_'.$this->langArr['lang']])?>
<?=showProp($this->item['note_occasion_'.$this->langArr['lang']])?>


</div>

<?php
function showProp($val,$lab=''){
  if ($val){
    if ($lab){
      $lab1=$lab.': ';
    }
    return $lab1.html_entity_decode($val).'<br>';
  }
}

function showText($textLang, $textDef, $curLang, $defLanguage,$header){
  $res=$textLang;
	if (!$res && $curLang!=$defLanguage){
	  $res=$textDef;
	}
	if ($res){
	?>
	<br><span class="t1"><?=$header?></span>:
	<br><?=$res?><br/>
<?php
	 }

}



function showList($val,$header1,$header2=''){
  if (isset($val)){
    ?>
<br>
<span class="t1"><?=$header1?></span>:<? if ($header2) print $header2;?>
<ul class="ul1">
<?php
$arr=explode("<br>",$val);
foreach($arr as $rn=>$row){
  ?>
	<li><?=$row?></li>
	<?php
}
?>
</ul>
<?php
  }
}

?>
