<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng">
<head>
<!-- Israeli Web Development -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title dir="rtl">Hundertwasser</title>
<meta http-equiv="content-language" content="en" />
<meta name="author" content="Hundertwasser" />
<link rel="shortcut icon" href="images/favicon.ico" />
<style>
body,html 
{
  padding:0;
  margin:0;
}
a 
{
text-decoration: none;
}

a:hover
{
text-decoration: underline;
}
.welcome
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #ACC790;

}
.bottom_links
{
color: #74C828;
text-decoration: none;
}
.bottom_links: hover
{
color: #74C828;
text-decoration: underline;
}

.sitemap_links
{
color: #959595;
text-decoration: none;

}
.sitemap_links : hover
{
color: #959595;
text-decoration: underline;

}

.bottom
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
}


</style>
</head>
<body class="InBody" id="top">
<script src="http://www.hw-archive.com/js/AC_RunActiveContent.js" type="text/javascript"></script>

<div id="clientDisplay">

<table cellpadding=0 cellspacing=0 width=1008 height=916 align=center>
<tr>
<td valign=top background=http://www.hw-archive.com/img/1.jpg>
  <table cellpadding=0 cellspacing=0 border=0>
  <tr>
  <td align=left valign=top width=372 >
  <script>
  function checkForm(frm){
    val=frm.elements['search_words'].value;
    //alert(val);
    if (val==''){
     alert('Please enter words to search');
     return false;
    }
    
    return true;
  }
</script>
  
  <!-- 
  <script type="text/javascript">
AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0','width','372','height','535','title','HunderrtWasser','src','http://www.hw-archive.com/flash/hw','quality','high','pluginspage','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash','movie','http://www.hw-archive.com/flash/hw' ); //end AC code
</script>
<noscript>
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="372" height="535"><param name="movie" value="http://www.hw-archive.com/flash/hw.swf" /><param name="quality" value="high" /><param name="menu" value="false" /><param name="wmode" value="" />
  <embed src="http://www.hw-archive.com/flash/hw.swf" wmode="" quality="high" menu="false" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="372" height="535"></embed></object>                           
                              </noscript> 
 -->                            
                              </td><td width=115></td>
<td valign=top>
<table cellpadding=0 cellspacing=0 width="516">
<tr>
<td bgcolor=#000000 valign=middle height="36">
<table bgcolor=#000000 cellpadding=0 cellspacing=0><tr><td align=center width=35>
<a href=/?lang=it><img border=0 src=http://www.hw-archive.com/images/english.jpg width=19 height=11></a></td>
<td width=35 align=center>
<a href=/?lang=ge><img border=0 src=http://www.hw-archive.com/images/lang2.jpg width=19 height=11></a></td>
<td width=75 align=center>
<a href=/?lang=en><img border=0 src=http://www.hw-archive.com/images/eng.jpg width=55 height=22></a></td>
</tr>
</table>

</td>
</tr>

<form name='search_form' onsubmit="return checkForm(this);" method="POST">
<tr>

<td bgcolor=#000000>
<input name="search_words" value="<?php print $this->search_words ?>" maxlength=25 type=text style="color:#ffffff; border: 0px; width:202px; height:28px; background-image: url(http://www.hw-archive.com/images/search.jpg);">
<input type="submit" value="&nbsp;" name="submit"
        onmouseout="this.style.backgroundImage='url(/images/btn_search.jpg)'" 
        onmouseover="this.style.backgroundImage='url(/images/btn_search2.jpg)'" 
        style="cursor:pointer;background-image:url(/images/btn_search.jpg);height:19px;width:102px;border:0;">

</td>
</form>
</tr>
<tr>
<td bgcolor=#000000 height=75 valign=bottom>
<img src="http://www.hw-archive.com/images/hundertwasser.jpg" />
</td>
</tr>
<tr>
<td ><table><tr><td width=30></td><td bgcolor=#000000 align=left><br><br><br><br>
<a href="/skin" onmouseover="document.skins.src='http://www.hw-archive.com/images/btn_skins_over.gif'" onmouseout="document.skins.src='http://www.hw-archive.com/images/btn_skins.gif'">
<IMG SRC="http://www.hw-archive.com/images/btn_skins.gif" NAME="skins" WIDTH="107" HEIGHT="48" BORDER="0" ALT="Skins"></a>
</td></tr></table>
</tr>
<tr>
<td ><table cellpadding=0 cellspacing=0><tr><td width=105></td><td bgcolor=#000000 align=left>
<a href="/shop.php" onmouseover="document.shop.src='http://www.hw-archive.com/images/btn_shop_over.jpg'" onmouseout="document.shop.src='http://www.hw-archive.com/images/btn_shop.jpg'">
<IMG SRC="http://www.hw-archive.com/images/btn_shop.jpg" NAME="shop" BORDER="0" ALT="Shop"></a>
</td></tr></table>
</tr>
</table>
</td>
  
  </tr>
  <tr>
<td colspan=3>
<table cellpadding=0 cellspacing=0 height=131 width="548" >
<tr><td height=28 colspan=2></td></tr><tr>
<td width=398></td>
<td bgcolor=#000000 valign=top>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/contact" onmouseover="document.contact.src='http://www.hw-archive.com/images/btn_contact_over.gif'" onmouseout="document.contact.src='http://www.hw-archive.com/images/btn_contact.gif'">
<IMG SRC="http://www.hw-archive.com/images/btn_contact.gif" NAME="contact" BORDER="0" ALT="Contact"></a><br>
<a href="/search" onmouseover="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search_over.jpg'" onmouseout="document.adsearch.src='http://www.hw-archive.com/images/btn_ad_search.jpg'">
<IMG SRC="http://www.hw-archive.com/images/btn_ad_search.jpg" NAME="adsearch"  BORDER="0" ALT="Advenced Search"></a>

</td>
</tr>
</table>
</td>
</tr>
  
  </table>
  <br>
  <table cellpadding=0 cellspacing=0 width=100%>
<tr>
<td height=70></td>
</tr>
<tr>
<td height=120>
<table cellpadding=0 cellspacing=0 width=100% height=120>
<tr>
<td width=210></td>
<td bgcolor=#000000 valign=top width="240" class=welcome>
<span style="vertical-align: super">
<b>Welcome to the Hundertwasser 
Online Museum.</b><br><br style="line-height:20px;">This is the place to find out more 
<br>
about the artist, his works, <br>
philosophy and life views.  

</span>  

</td><td class=welcome bgcolor=#000000 valign=top>
<span style="vertical-align: super">Browse through the <a class=bottom_links href="doc.html">online 
<br>
documentation</a>, join the <a class=bottom_links href="forum/">forum</a> or purchase <br>
on of the many posters, books and <br>
reproductions available on our official <br>
<a class=bottom_links href="shop.php">online shop</a>. 
<br>
We hope you enhoy your visit.</span></td>
<td width=35></td>
<td width="228" bgcolor=#000000 valign=top class=welcome>
<marquee direction='down' style="height:100px;">
<span style="vertical-align: super"><font color=#CFD58F>Here comes the news ticker
<br>
text which includes events, news <br>
& current announcments to a 
maximum size represented 
<br>
By this  short text.
<br>
The news items will switch.</font></span>
</marquee>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td>
<br><br><br><br><br><br>
<table bgcolor=#000000 width="871"><tr><td colspan=6 height=120></td></tr>
<tr >
<td width=26 bgcolor=#000000></td>
<td class=bottom bgcolor=#000000>
<font color=577A34>All contents   &copy; 2007</font>
</td>
<td width=50 bgcolor=#000000></td>
<td class=bottom><font color=908F8F>
Design: <a target=_blank class=sitemap_links href="http://www.galordesign.com">galordesign</a> || Powered By : 
<a target=_blank class=sitemap_links href="http://www.mad-logic.com">MadLogic</a></font>
</td>
<td width=50 bgcolor=#000000></td>
<td class=bottom bgcolor=#000000><font color=908F8F>
<a class=sitemap_links href="/sitemap.html">Site Map</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a  class=sitemap_links href="/terms.html">Terms Of Use</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="/support.html">Support</a></font>  <font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="/links.html">Links</a></font>  <font color=#D8DA83>||</font><font color=908F8F>
<a class=sitemap_links href="/contact">Contact Us</a>  </font></td>
</tr>
</table></td></tr>
</table>

</td>

</tr>
</table>
</div>

</body>
</html>
  
    