<!--Hundertwasser-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<?php echo $this->HeadMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php print $this->headScript();?>
<meta name="description" content="Hudertwasser skins paintings architecture video applied art graphics" />
<link rel="shortcut icon" href="/images/favicon.ico" />
</head>
<body>
<table class="tab1">
	<tr>
		<td  class="tab1TD1"><!--   FLASH   -->
			<div id="mainf" class="">
				<div id="flashcontent1">
					<br />
					<br />
					Your browser does not support Flash technology.<br /><span>To install Flash Player
					<a href="http://get.adobe.com/flashplayer/" class="l4" >
						click here
					</a>.
					<br /></span>
				</div>
				<script type="text/javascript">
				var so = new SWFObject("/images/main.swf", "mySwfID1", "507", "530", "8", "#Ffffff");
				so.addParam("scale", "noborder");
				so.addParam("salign", "tl");
				so.addParam("wmode", "transparent");
				so.write("flashcontent1");
				</script>
			</div>

		</td>
	</tr>
	<tr>
		<td  class="tab1TD2">
		<img src="/images/trans.gif" width="800" height="1" alt="hundertwasser" />
			<div class="hpT1"><!--   TEXT 1   -->
				<b>H</b>undertwasser, a visionary and responsible creator, mobilizes the power of his art in order to spread his message for a life in harmony with nature and the individual creativity.
<br /><br />
He is a symbolic figure for a non-conformist way of life, a forerunner of environmental protection and an ambassador for a self-determined alternative existence. 
				<br /><img src="images/trans.gif" width="1" height="185" alt="hundertwasser"/>
			</div>
			<div class="hpT2"><!--   TEXT 2   -->
				<b>D</b>iscover Hundertwasser&rsquo;s world, his vision, his ideals and his message in 
<a href="/skin" class="l12">the 5 skins</a> pictogram. 
<br /><br />
Experience Hundertwasser&rsquo;s work &minus; 
click on <a href="/oeuvre" class="l12">The Oeuvre</a>.
<br /><br />
Find detailed records - click on <a href="/documentation" class="l12">Documentation</a>.
			</div>
			<div class="hpT3"><!--   NEWS REEL   -->
<!--				Here comes the news ticker-->
<!--				text which includes events, news-->
<!--				&amp; current announcments to a maximum size represented-->
<!--				By this short text.-->
<!--				The news items will switch.-->
			</div>
			<div id="top1">
				<div id="top1_1"><!--   LANGUAGES   -->
<!--					<a href="#"><img src="/images/flag_fr.gif" alt="French" /></a>-->
					<a href="#"><img src="/images/flag_ger.gif" alt="German"  border='0' title="In construction. Will be enabled soon."/></a>
					<a href='/?lang=en'><img src="/images/flag_eng.gif" alt="English" border='0' /></a>
				</div>
				<div id="top1_2"><!--   SEARCH   -->
					<form action="/item/object-list/" name="hpSeacrh" id="hpSeacrh" method="get">
						<div class="top1_2a">
							<input name="free_text" type="text" class="input1" />
						</div>
						<div class="top1_2b">
							<div onClick="javascript:document.hpSeacrh.submit();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image1','','/images/btn_search_over.gif',1)">
							 	<img src="/images/btn_search.gif" alt="Quick Search" name="Image1" id="Image1" />
							 </div>
						</div>
					</form>
				</div>
				<div id="top1_3" title=""><img src="/images/logo1.gif" alt="Hundertwasser" /></div><!--   LOGO   -->
				<div id="top1_8" title=""><!--   OUEVRE   -->
					<div onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image6','','/images/btn1_2.gif',1)">
						<a href="/oeuvre"><img  src="/images/btn1_1.gif" alt="The Ouevre" name="Image6" id="Image6" /></a>
					 </div>
				</div>
				<div id="top1_4" title=""><!--   SKINS   -->
					<div onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image2','','/images/btn2_2.gif',1)">
						<a href="/skin"><img  src="/images/btn2_1.gif" alt="Skins" name="Image2" id="Image2" /></a>
					 </div>
				</div>
				
				<div id="top1_5b" title=""><!--   Documentation   -->
					<div onmouseover="MM_swapImage('Image3b','','images/btn3_2.gif',1)" onmouseout="MM_swapImgRestore()">
						<a href="/documentation"><img id="Image3b" name="Image3b" alt="Documentation" src="/images/btn3_1.gif"/></a>
					 </div>
				</div>
				<div id="top1_5" title=""><!--   SHOP   -->
					<div onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image3','','/images/btn4_2.gif',1)">
						<a href="#"><img  src="/images/btn4_1.gif" alt="Shop" name="Image3" id="Image3" /></a>
					 </div>
				</div>
				
				<div id="top1_6" title=""><!--   CONTACT US   -->
					<div onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image4','','/images/btn5_2.gif',1)">
						<a href="/contact"><img  src="/images/btn5_1.gif" alt="Contact Us" name="Image4" id="Image4" /></a>
					 </div>
				</div>
				<div id="top1_7" title=""><!--   ADVANCED SEARCH   -->
					<div onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image5','','/images/btn6_2.gif',1)">
						<a href="/search"><img  src="/images/btn6_1.gif" alt="Advanced Search" name="Image5" id="Image5" /></a>
					 </div>
				</div>
			</div>
		</td>
	</tr>
	<tr>
		<td  class="footer"><!--   FOOTER   -->
			<div class="f1">All content &copy; 2009</div>
<div class="f2">
	Design: <a href="http://www.galordesign.com" class="l2">Galordesign</a> |&nbsp;| Powered By: <a href="http://www.mad-logic.com" class="l2">Madlogic</a>
</div>
<div class="f3">
	<a href="#" class="l3">Home Page</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Site Map</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Terms Of Use</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Support</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="#" class="l3">Links</a>&nbsp;&nbsp;|&nbsp;|&nbsp;&nbsp;
	<a href="/contact" class="l3">Contact Us</a>	<br/>
	
	<a href="deutsch/hundertwasser/hwueberhw.php" class="hw">Hundertwasser &uuml;ber Hundertwasser</a>
	<a href="deutsch/hundertwasser/biographie.php" class="hw">Biographie</a>
	<a href="deutsch/werk/malerei/malerei.php" class="werk">Malerei</a>
	<a href="deutsch/werk/graphic/graphik.php" class="werk">Graphik</a>
  	<a href="deutsch/werk/tapis/tapisserie.php" class="werk">Tapisserie</a>
  	<a href="deutsch/werk/ankunst/angewandtekunst.php" class="werk">Angewandte Kunst</a>
  	<a href="deutsch/werk/arch/architektur.php" class="werk">Architektur</a>
  	<a href="deutsch/werk/eco/oekologie.php" class="werk">&Ouml;kologie</a>
	<a href="deutsch/texte/philosophie.php" class="txt">Hundertwasser Manifeste und Texte</a>
	<a href="deutsch/texte/literatur.php" class="txt">Literatur zu Hundertwasser</a>
	<a href="deutsch/ausstellungen/hw_im_khw.php" class="exhib">Hundertwasser im KunstHausWien</a>
    <a href="deutsch/ausstellungen/ausstellungsprogramm.php" class="exhib">Ausstellungsprogramm</a>
    <a href="deutsch/ausstellungen/Wcd47b505e67a0.htm" class="exhib">Ausstellungen Archiv</a>
	<a href="deutsch/hundertwasser/hwueberhw.php" class="hw">HUNDERTWASSER</a>
	<a href="deutsch/werk/cover.php" class="werk">WERK</a>
	<a href="deutsch/texte/philosophie.php" class="txt">TEXTE</a>
    <a href="deutsch/ausstellungen/index.php" class="exhib">AUSSTELLUNGEN</a>
    <a href="deutsch/news/index.php" class="news">NEWS</a>
    <a href="deutsch/kontakt.php" class="contact">KONTAKT</a> 
    <a href="deutsch/impressum.php" class="impressum">IMPRESSUM</a>
	<a href="index_en.php" class="other">ENGLISH</a>
	<a href="deutsch/hundertwasser/hwueberhw.php"><img src="interface/cover/cover_m_de_0_0.png" alt="Hundertwasser" name="hundertwasserTit" width="206" height="67" id="hundertwasserTit" /></a>
	<a href="deutsch/werk/cover.php" ><img src="interface/cover/cover_m_de_1_0.png" alt="Werk" name="werkTit" width="74" height="31" id="werkTit" /></a>
	<a href="deutsch/texte/philosophie.php"> <img src="interface/cover/cover_m_de_2_0.png" alt="Texte" name="TexteTit" width="79" height="37" id="TexteTit" /></a>
	<a href="deutsch/ausstellungen/index.php"> <img src="interface/cover/cover_m_de_3_0.png" alt="Ausstellungen" name="Ausstellungen" width="219" height="65" id="Ausstellungen" /></a>
	<a href="deutsch/news/index.php" ><img src="interface/cover/cover_m_de_4_0.png" alt="News" name="NewsTit" width="79" height="37" id="NewsTit" /></a>
	<a href="deutsch/kontakt.php" ><img src="interface/cover/cover_m_de_5_0.png" alt="Kontakt" name="KontaktTit" width="122" height="31" id="KontaktTit" /></a>
	<a href="deutsch/impressum.php" ><img src="interface/cover/cover_m_de_6_0.png" alt="Impressum" name="ImpressumTit" width="96" height="26" id="ImpressumTit" /></a>
	<a href="http://www.miibeian.gov.cn" target="_blank">苏ICP备10200431号-2</a>
	
</div>		</td>
	</tr>
</table>
</body>
</html>
