<!--Hundertwasser-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<?php echo $this->HeadMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php print $this->headScript();?>
<meta name="description" content="Hudertwasser skins paintings architecture video applied art graphics" />
<link rel="shortcut icon" href="/images/favicon.ico" />
</head>
<body>
<div id="landing1">

    <h3>The Hundertwasser Non-Profit Foundation </h3>

    invites you to visit the New Hundertwasser online Universe<br />

    and participate in the formation of its final content and design.<br />

    We welcome any comment, remark, suggestion, and critique you might have.<br />

    Please use the “contact us” form for your message.<br />

    <a href="/">click to ENTER</a>

    <div id="landing2">

        <h3>Die Hundertwasser Gemeinnützige Privatstiftung </h3>

        lädt Sie herzlich ein, die neue Hundertwasser Online-Enzyklopädie <br />

        zu besuchen und an der Ausformung ihrer endgültigen Gestalt teilzuhaben. <br />

        Wir begrüßen jede kritische Anmerkung und kreative Anregung, <br />

        die Sie uns über „contact us“ zukommen lassen.<br />

        Derzeit ist die website in englischer Sprache vorhanden,<br /> 

        die deutsche Version wird in Kürze verfügbar sein.<br /> 

        Wenn Sie benachrichtigt werden wollen, senden Sie uns Ihre Email-Adresse.<br />

        <a href="/">click to ENTER</a>

    </div>

</div>
</body>
</html>