<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng">
<head>
<!-- Israeli Web Development -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title dir="rtl">&nbsp;Galor Design - Israeli Web Development || Registered Clients</title>
<meta name="description" content="Password Protected Zone" />
<meta http-equiv="content-language" content="en" />
<meta name="author" content="Galor Design - Israeli Web Development, Tel Aviv, 972 3 6204082" />
<meta name="reply-to" content="info@galordesign.com" />
<link rel="shortcut icon" href="images/favicon.ico" />
</head>
<body class="InBody" id="top">
<style>
body,html
{
  padding:0;
  margin:0;
}
a
{
text-decoration: none;
}

a:hover
{
text-decoration: underline;
}
.welcome
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #ACC790;

}

.related_items
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #878D8A;
font-weight: bold;
text-decoration: underline;
}


.related_items a
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #878D8A;
text-decoration: underline;
font-weight: bold;
}

.related_items a:hover
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:12px;
color: #878D8A;
text-decoration: none;
font-weight: bold;
}

.bottom_links
{
color: #74C828;
text-decoration: none;
}
.bottom_links: hover
{
color: #74C828;
text-decoration: underline;
}

.sitemap_links
{
color: #959595;
text-decoration: none;

}
.sitemap_links : hover
{
color: #959595;
text-decoration: underline;

}

.bottom_click
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:13px;
}

.bottom
{
font-family: Verdana,Arial,Helvetica,sans-serif;
font-size:10px;
}

.bg
{
background-image: url(http://www.hw-archive.com/images/slideshow_bg.jpg);
repeat: no-repeat;
width: 1008;
height: 987;
}


</style>

</head>
<body>

<table cellpadding=0 cellspacing=0 align=center width=1008 height=987>
<tr>
<td class=bg valign=top>

<table cellpadding=0 cellspacing=0 align=left width=100%>

  <tr><td>
  <!-- Start Top Menu -->
  <table cellpadding=0 cellspacing=0   align=left>
  <tr>
  <td colspan=2 height=87></td>
  </tr>
  <tr>
  <td style="width:218px;">
  </td>

  <td>
  <table width=450><tr><td valign=top width="45"><br style="line-height:7px;">
          <a href="/" onmouseover="document.home.src='http://www.hw-archive.com/images/btn_home_over.jpg'" onmouseout="document.home.src='http://www.hw-archive.com/images/btn_home.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_home.jpg" NAME="home" BORDER="0" ALT="Home"></a>
        </td>
        <td valign=top width="74"><br style="line-height:3px;">
            <a href="/skin" onmouseover="document.skins.src='http://www.hw-archive.com/images/btn_skins_over.jpg'" onmouseout="document.skins.src='http://www.hw-archive.com/images/btn_skins.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_skins.jpg" NAME="skins" BORDER="0" ALT="Skins"></a></td>
        <td width="84">

          <a href="/shop.php" onmouseover="document.shop.src='http://www.hw-archive.com/images/btn_shop_over.jpg'" onmouseout="document.shop.src='http://www.hw-archive.com/images/btn_shop.jpg'">
        <IMG SRC="http://www.hw-archive.com/images/btn_shop.jpg" NAME="shop" BORDER="0" ALT="Shop"></a>
        </td>
        <td valign=top width="85"><br style="line-height:6px;">
          <a href="/contact.php" onmouseover="document.contact.src='http://www.hw-archive.com/images/btn_contact_over.gif'" onmouseout="document.contact.src='http://www.hw-archive.com/images/btn_contact.gif'">
        <IMG SRC="http://www.hw-archive.com/images/btn_contact.gif" NAME="contact" BORDER="0" ALT="Contact"></a>
        </td>
        <td valign=top><a href="/search">
        <IMG SRC="http://www.hw-archive.com/images/btn_ad_search_over.jpg" NAME="adsearch" BORDER="0" ALT="Advanced Search"></IMG></a>

        </td>
        </tr></table>
        <!-- End Top Menu -->
  </td></tr>
  </table>

  </td></tr>
  <tr>
  <td height=88 valign=bottom style="padding-left:35px;">

  <a href="/">
  <font color="#878d8a" face="Verdana" size="2"><b><u>
  Home</u></b></font></a>
  <font color="#d45232"> <font size="1" face=verdana>&gt;</font>
  <a href="/search">
  <font color="#878d8a" face="Verdana" size="2"><b><u>
  Advanced Search</u></b></font></a><font face="Verdana" size="1"> &gt;</font> <a href="/searchresults/index/type/<?=$this->work ?>">

  <font color="#878d8a" face="Verdana" size="2"><b><u>
  Search item results</u></b></font></a>
  <font size="1" face=verdana> &gt;</font>
  <font face="Verdana" size="2">Slide Show View</font></font></td>
  </tr>
  <tr>
<td>
<br><br>

<?=$this->layout()->content ?>

</td>
</tr>

<tr>
<td>

<br>
<br>
<br>
<table>
<tr >
<td width=35 ></td>
<td class=bottom>
<font color=577A34>All contents   &copy; 200777</font>
</td>
<td width=50 ></td>
<td class=bottom><font color=908F8FDesign: <a target=_blank class=sitemap_links href="http://www.galordesign.com">galordesign</a> || Powered By :

<a target=_blank class=sitemap_links href="http://www.mad-logic.com">MadLogic</a></font>
</td>
<td width=50 ></td>
<td class=bottom ><font color=908F8F>
<a class=sitemap_links href="sitemap.html">Site MapMap</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a  class=sitemap_links href="terms.html">Terms Of Use</a>  </font><font color=#D8DA83>
||</font><font color=908F8F>
<a class=sitemap_links href="support.html">Support</a></font>  <font color=#D8DA83>

||</font><font color=908F8F>
<a class=sitemap_links href="links.html">Links</a></font>  <font color=#D8DA83>||</font><font color=908F8F>
<a class=sitemap_links href="contact.php">Contact Us</a>  </font></td>
</tr>
</table>

</td>
</tr>
</table>
</td>
</tr>

</table>

</body>
</html>

