<table width="100%" border=0>
<tr>
<td  valign=top><br>
  <br>
  <form method=post name=contactForm action=contact.php>
  <table cellpadding=0 cellspacing=0 >
  <tr>
  <td  valign=top style="padding-left:30px; padding-right:5px;">
  <table width="527">
  <tr>
  <td width="237" valign=top>
  <br>
  <b><font color="#D45232" face="Verdana" size="2">Name:&nbsp;&nbsp;&nbsp; &nbsp;
  </font></b> <input type=text class=input_a name=name id=name>
  <br><br><b><font color="#D45232" face="Verdana" size="2">Country: </font></b> &nbsp;<input type=text class=input_a name=country id=country>
  </td>
  <td valign=top width=280>
  <br>
  <b><font color="#D45232" face="Verdana" size="2">Surname:&nbsp; &nbsp;</font></b><input type=text class=input_a name=surname id=surname>
  <br><br>
  <b><font color="#D45232" face="Verdana" size="2">Email:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font></b> &nbsp;<input type=text class=input_a name=email id=email>
  </td>
  </tr>
  <tr>
  <td colspan=2 valign=top><b><font color="#D45232" face="Verdana" size="2">Message:</font></b> 
  <textarea name message class=input_b >
  
  </textarea>
  </td>
  </tr>
  <tr>
  <td colspan=2 style=:padding-left:75px;">
  <input type=submit value=Send name submit style="background:#0C0C0C; font-weight:bold; color:#9E3B79; border-width: 0px;">
    
  </td>
  </tr>
  </table>
</td><td valign=top width="194"> <b><font face="Verdana" size="2"><font color="#ACC790">Hundertwasser Museum<br>
  somename 14 st.<br>
  Vienna 23545 <br>
  Austria<br><br>
  <br>
  Tel: 455 34 34536<br>
  Fax: 234 53 34556<br>
  </font><a href="mailto:info@hundertwasser.co.au"><font color="#ACC790">info@hundertwasser.co.au</font></a></font></b><font color="#D8DA83">
  <br>
&nbsp;</font></td>
  </tr>
  <tr>
  <td colspan=2>
  
  </td>
  <td width="1"></td>
  </tr>
  </table></form>
  

</td>
</tr>

</table>