<?
$work_id=$this->placeholder('work_id');
$title_fld=$this->placeholder('title_fld');
$date_fld=$this->placeholder('date_fld');
//print "date_fld:".$date_fld;
?>
  <table border=0>
  <tr>
  <td width=30></td>
  <td valign=top width=530 height=96 background=http://www.hw-archive.com/images/pic_bg.jpg>
  <table border=0 cellpadding=0 cellspacing=0 width="497">

  <tr>
  <td style="padding-left:35px;" width="135">
  <a href="/<?=$this->placeholder('work')?>/item/id/<?=$this->escape($this->$work_id)?>">
  <?if ($this->img){ ?>
  <img border=0 src="<?=$this->img?>">
  <?}else{
  ?>	
<img border=0 src=http://www.hw-archive.com/images/pic1.jpg>
<?
}
?></a>
  </td>
  <td><b><font face="Verdana" size="2" color="#7AC633">
  <a style="color:#7AC633;font-size:13px;font-family:Verdana;" href="/<?=$this->placeholder('work')?>/item/id/<?=$this->escape($this->$work_id)?>"><?=$this->escape($this->$title_fld).' - '.$this->$date_fld?></a></font>
  </td>
  </tr>

  </table>
  </td>
  </tr>
  </table>