<div style="height:95px;overflow:none;">

<table cellpadding=0 cellspacing=0 width="595" border=0>
<tr>
<td width=7></td>
<td class=welcome valign=top style="padding-left:6px; padding-top:6px; background-image:url(/images/skins_title_bg.jpg); background-repeat: no-repeat;">
<div style="width:165px; height:70px; overflow:hidden;">

<font color="#7CC433" font size="2"> 
<?=$this->hlpFormatText($this->maintitle_name)?>
</font>
</div>
</td>
<td valign=top class=welcome width="398" style="padding-left:6px; padding-top:6px; background-image:url(/images/skins_text_bg.jpg); background-repeat: no-repeat;">
<div style="width:390px; height:70px; overflow:hidden;">
<?=$this->hlpFormatText($this->rel_highlight,255)?></font>
<a href="/text/item/id/<?=$this->text_id?>"><font color="#4B4E4D"><b>
<u>Full&nbsp;text</u></b></font></a></div></td></tr></table>
<img src=/images/sep.jpg>
</div>