<tr><!--BREADCRUMB PATH-->
<td class="" style="height: 136px; background: url(&quot;/images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;">
	<div id="bcPath">
	<a href="/" class="l4 b">Home Page</a> &gt;	<span class="l4on">The 5 Skins</span>
	</div>
</td><!--border:1px red solid;-->

<td style="background: url(&quot;/images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">

<div id="skins_flash"><!--SKINS FLASH-->

<div id="skins_flash2">
<div id="flashcontent1"><br />
<br />
Your browser does not support Flash technology.<br />
<span>To install Flash Player <a href="http://get.adobe.com/flashplayer/" class="l4"> click here </a>. <br />
</span></div>

<script type="text/javascript">
					var so = new SWFObject("/images/skins/skins.swf", "mySwfID1", "435", "580", "8", "#Ffffff");
					so.addParam("scale", "noborder");
					so.addParam("salign", "tl");
					so.addParam("wmode", "transparent");
					so.write("flashcontent1");
					</script></div>
</div>
</td>
</tr>
<tr>
<td class="inT4" colspan="2">
<div id="inT4b" style="background: url(/images/advanced_search/top_6.jpg) left top no-repeat;">

<div class="textBox1">

<span style="font-size:18px;color:#508416;">A general guide to the themes, ideas and ideals, writings and works of Hundertwasser in relation to the 5 skins.</span> <br/><br/><br/>
<span class="b">The art historian <span style='font-weight:normal;font-style:italic'>Pierre Restany</span> writes in his book <span style='font-weight:normal;font-style:italic'>The Power of Art, Hundertwasser, The Painter-King with the Five Skins:</span> </span> <br />
<br />
For Hundertwasser, man has three skins: his natural <a href="/epidermis" class="l5">epidermis</a>, his <a href="/clothes" class="l5">clothes</a>, his <a href="/houses" class="l5">house</a>.
When in 1967 and 1968 the artist delivered his “Naked” address to proclaim man’s right to his third skin (the free alteration of his <a href="/houses" class="l5">house</a>),
 he accomplished the ritual full cycle of his spiral. 
 <br />He re-found his first skin, that of his original truth,
 his nakedness as a man and painter, by stripping off his second skin (his <a href="/clothes" class="l5">clothes</a>) to proclaim the right to his third skin (his <a href="/houses" class="l5">home</a>).
 <br /><br />Later, after 1972, when the major ideological turning-point had been passed, the spiral of Hundertwasser’s chief concerns began to unfold.
 His consciousness of being was enriched by new questions, which called for fresh responses and elicited new commitments.
 So appeared the new skins that were to be added to the concentric envelopment of the three previous ones.
 Man’s fourth skin is the <a href="/identity" class="l5">social environment</a> (of family and nation, via the elective affinities of friendship).
 The fifth skin is the <a href="/earth" class="l5">planetary skin</a>, directly concerned with the fate of the biosphere,
 the quality of the air we breathe, and the state of the earth’s crust that shelters and feeds us.
 <br />
<br />
<span style="color:#508416;">Click on the 5 skins pictogram to find out about the 5 skins.</span> <br />

<br />
<?php /*?>
<span class="green">Click a skin on the image</span><span class="orange">
to view the skin's related texts >></span>
<?*/?>
</div>

</div>

</td>
</tr>