<?php if (false){?>
<script>
<?php
$this->jQuery()->onLoadCaptureStart();
}
?>
/*
jQuery("a.mt-hl").mouseover(function(){

  var tmpArr=jQuery(this).attr('id').split('-');
  var divId=tmpArr[2];
  jQuery("div.mt-summary").hide();
  jQuery("div#mt-summary-"+divId).animate({height:'toggle',opacity:'toggle'},{duration:'slow'});


});
*/
//jQuery(".mt-summary").

<?php
$this->jQuery()->onLoadCaptureEnd();
if (false){
?>
</script>
<?php }?>
<tr><!--BREADCRUMB PATH-->
		<td class="" style="height: 136px; background: url(&quot;/images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;">
			<div id="bcPath">
				<a href="/" class="l4 b">Home Page</a> &gt;
				<a href="/skin" class="l4">The 5 Skins</a> &gt;
				<span class="l4on"><?=$this->skinProps['title_long_'.$this->langCode]?></span>
			</div>

		</td>
		<td>
			<div class="bcPath3" title="" style="background: url(&quot;/images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">&nbsp;</div>
		</td>
	</tr>
<tr>
<td colspan="2">
<div style="float: right;">
<div class="" id="rightBlock">
<div id="RB1"><img alt="<?=$this->l('Related Items')?>"
	src="/images/items/tit_rel_eng.gif" /></div>
<div id="RB1Cat">
<div id="RB2"><?php
$langArr=$this->sess('langArr');
//print_r($langArr);
foreach($this->relLink as $id=>$link){
  ?>
<div style='z-index:100000;'
	onmouseover="MM_swapImage('ImageRB<?=$id?>','','/images/icons/tit_<?=$link['name']?>_on_<?=$langArr['lang_alt']?>.gif',1)"
	onmouseout="MM_swapImgRestore()"><a href="/<?=$this->skinName.'/'.$link['link']?>"> <img alt="<?=$link['title']?>" src="/images/icons/<?=$link['name']?>.gif" />
<img id="ImageRB<?=$id?>" name="ImageRB<?=$id?>"
	alt="<?=$link['title']?>"
	src="/images/icons/tit_<?=$link['name']?>_<?=$langArr['lang_alt']?>.gif" />
</a>(<?=$link['cnt']?>)</div>
  <?php
}

?> <br />
<br />
 </div>
<div title="" id="RB1Cat2"> </div>
</div>
<div class="" id="RB1Cat3">
<div id="RB3"><!--<img src="/images/items/buy_eng.gif" alt="Related Shop Products" />-->
<div class="newCrazy1">Buy Me!</div>
<span class="newCrazy2">Related Shop Products</span>
<div id="RB4">
<?php
$cnt=sizeof($this->buyItems);
$num=$cnt-1;
for($i=0;$i<$cnt;$i++){
  $srcEnc=urlencode($this->buyItems[$i]['image_path']);
  if ($i % 3==0){
  ?>
<div class="ThumbRow clearRow">
<?php
  }
  ?>
<div>
<!--  <a class="111" target='_blank' href="http://hw-archive.com/shop/product.php?productid=<?=$this->buyItems[$i]['id']?>&cat=<?=$this->buyItems[$i]['categoryid']?>&page=1">
  <img alt="<?=substr($this->buyItems[$i]['descr'],0,30)?>" src="shop<?=substr($this->buyItems[$i]['image_path'],1)?>" height="32" width="32"><span><?=substr($this->buyItems[$i]['descr'],0,30)?></span></a>-->
</div>
  <?php
  if ($i % 3==2 OR $i==$num){
  ?>
</div>
 <?php
  }
}
?>
 </div>
<a id="shopLink" class="l10" target="_blank"
	href="http://hw-archive.com/shop">Visit Online Shop</a>
<div id="RB1Cat4"> </div>
</div>
</div>
</div>


</div>
<div>
<div id="inCatItems">
<a href="#" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Imageskin','','<?=$this->skinIcon;?>_2.png',1)" >
 <img src="<?=$this->skinIcon;?>_1.png" 
 alt="<?=$this->skinProps['title_long_'.$this->langCode]?>" 
 name="Imageskin" id="Imageskin" class="hwskintit"></a>  

<br/>
<div class="skinsPre">
<?php print html_entity_decode($this->skinProps['descr_'.$this->langCode],ENT_QUOTES,'UTF-8')?>
</div>
  <?php

  foreach($this->pager as $item){
    if ($this->skinProps['skin']){
      $CatItem2_color="CatItem2_color".$this->skinProps['skin'];
      $CatItem3_color="CatItem3_color".$this->skinProps['skin'];
      $CatItem4_color="CatItem4_color".$this->skinProps['skin'];
    }else{
      $CatItem2_color="";
      $CatItem3_color="";
      $CatItem4_color="";
    }
    
    $mtSummary=$item["maintitle_summary_{$this->langCode}"];
    $mtSummary=str_replace('&nbsp;',' ',$mtSummary);
    $mtSummary=strip_tags(html_entity_decode($mtSummary,ENT_QUOTES,'UTF-8'));

    $mtSummary=preg_replace('/[\\s]+/'," ",$mtSummary);

    ?>
<div class="CatItem1">
<div class="CatItem2 <?=$CatItem2_color?>"></div>
<div class="CatItem3 CI3noPad CatItem3b <?=$CatItem3_color?>"
	title="<?php print $item["maintitle_name_{$this->langCode}"];?>">
<div><a href="/highlights/<?php print $item['mt']?>" class="l12 mt-hl"
	id='mt-hl-<?php print $item['mt']?>'><span><?php print $item["maintitle_name_{$this->langCode}"];?></span></a>
<br />
<div id='mt-summary-<?php print $item['mt']?>' class='mt-summary'
	style='display: block;'><a href="/highlights/<?php print $item['mt']?>"><?php print $mtSummary;?></a>
<br />
</div>
</div>
</div>
<div class="CatItem4 <?=$CatItem4_color?>"></div>
</div>
    <?php
  }
  /*uncomment if you need paging
   ?>
   <div id="catPaging"><!--ITEM PAGING--> <?php
   echo $this->paginationControl($this->pager,'Sliding', 'skin/pages.phtml');
   */
  ?></div>
</div>
</td>
</tr>



