<tr><!--BREADCRUMB PATH-->
<td class="" style="height: 136px; background: url(&quot;/images/advanced_search/top_4.jpg&quot;) no-repeat scroll left top transparent;">
	<div id="bcPath">
	<a href="index.php" class="l4 b">Home Page</a> &gt;	<span class="l4on">The 5 Skins</span>
	</div>
</td><!--border:1px red solid;-->

<td style="background: url(&quot;/images/advanced_search/top_5.jpg&quot;) no-repeat scroll left top transparent;">

<div id="skins_flash"><!--SKINS FLASH-->

<div id="skins_flash2">
<div id="flashcontent1"><br />
<br />
Your browser does not support Flash technology.<br />
<span>To install Flash Player <a href="http://get.adobe.com/flashplayer/" class="l4"> click here </a>. <br />
</span></div>

<script type="text/javascript">
					var so = new SWFObject("/images/skins/skins.swf", "mySwfID1", "435", "580", "8", "#Ffffff");
					so.addParam("scale", "noborder");
					so.addParam("salign", "tl");
					so.addParam("wmode", "transparent");
					so.write("flashcontent1");
					</script></div>
</div>
</td>
</tr>