<td class="" colspan="2"><!--CONTACT FORM-->
<div id="inContact" title="" style="background:url(/images/advanced_search/top_6.jpg) left top no-repeat;">
				<br/><br/><br/>
<div class="b" style="padding-left:100px;padding-top:20px;" >
<?=$this->l('Your message was successfully sent.Thanks!')?>
</div>
			</div>
			<div id="inContact2" title="">
				<br/><span class="b">THE HUNDERTWASSER <br/>NON PROFIT FOUNDATION</span>
				<br/><br/>Address:
				<br/>P.O. Box 28
				<br/>1182 Vienna 
				<br/>Austria / Europe
				<br/><br/>Contact: 
				<br/>T +43 (0)1 470 12 12
				<br/>F +43 (0)1 470 90 90
				<br/>E <script>document.write('<a href="mailto:o'+'ffi'+'ce@ha'+'rel.a'+'t"'+ 'class="l6">office [at] harel.at</a>');</script>

			</div>

</td>